### ISSUE TITLE
Component: Formidable Pro integration

### ISSUE THREAD

**Issue by qrahaman** [pods-framework/pods#101]
Hello Scott,

This is based on your Gravity forms component pursuit.  At some point, could you consider doing the same for Formidable Pro?  Thanks!

**Comment by iCristiano** [comment]
Any news about that?

**Comment by sc0ttkclark** [comment]
I don't use it myself, so that's pretty much halted most of my ability to work on it in my free time, but we've built a couple of forms integration now between [Pods Gravity Forms](https://github.com/pods-framework/pods-gravity-forms) and [Pods Caldera Forms](https://github.com/pods-framework/pods-caldera-forms), but this will still require someone who is very familiar with Formidable Pro and knows their way around how to map field submissions.

I also no longer have a license, so we'd need to get one we could use for testing purposes.

For further discussion, feel free to join our [Pods Slack](http://pods.io/chat/) and hop into the #dev-integration channel.

**Comment by tomherold** [comment]
@Scott
I have a developer license for Formidable and use it since years. Contact me here to get the ball rolling:
http://www.evolvingwealth.org/contact/

**Comment by sc0ttkclark** [comment]
Sent :)

**Comment by tomherold** [comment]
Happy to help testing - see my private email to you.

**Comment by codente** [comment]
+1 for this.  Would love to see it happen.

**Comment by codente** [comment]
Happy to report that mapping FP form fields to Pods fields when creating a new post actually works now without a plugin. 

Just have to manually add the name of your custom field into the form settings under Create Post form action.  Happy to explain more for anyone who needs it.

**Comment by tomherold** [comment]
@codente 
Yes, please - if possible can you post a short example of your code...

**Comment by jimtrue** [comment]
@codente Does it work as seamlessly with Relationship Fields and Custom Taxonomy as well?

**Comment by codente** [comment]
@tomherold there is no code.  I can write up something later this week though
@jimtrue I haven't tested that yet.  It's not flawless though.  Will be adding a ticket/issue to Git per Scott so it can be looked into

**Comment by jimtrue** [comment]
#3930 for reference
