### ISSUE TITLE
Clear Pods cache if rewrite slug is changed

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#1401]
I started moving comparisons from their own post type and into the docs, but the old post type was still picking up the page.  I changed the rewrite slug to "not/docs/comparisons" as a quick and easy way to stop that without making other changes just yet, but had to clear cache before it took effect.

**Comment by pcfreak30** [comment]
I had a weird issue were despite having a slug defined in an extended post type, it wasn't being put in affect despite flushing the rewrite rules. After clearing pods cache it worked. Pods shouldn't be interfering with pods type properties on an extended post type.

Another odd thing is when I disabled the plugin registering the CPT, it still showed up registered due to pods.
