### ISSUE TITLE
Combination of columns in relation PICK drop down

### ISSUE THREAD

**Issue by wreciak** [pods-framework/pods#1503]
Hi
Is there some way how to show combination of more columns in  relation PICK?
I tried many combinations of magic tags like {@id}{@name} etc, but this don't work. I did not find solution for this in documentation.
Thanks
Martin

**Comment by jimtrue** [comment]
@sc0ttkclark @pglewis How hard would this be to implement since we've revisited the Relationships as part of 2.7 (rewrote the fields). Is it possible to just run a display across the contents of the 'Display in Select Field'? Would handle a lot of requests for folks that need this field to be more informative.
