### ISSUE TITLE
Additional Taxonomy Options: Make Required and Single Selection Only

### ISSUE THREAD

**Issue by mirkanu** [pods-framework/pods#1515]
Would it be possible to add functionality to taxonomies as follows:
1. Make [this] taxonomy required: Force the user to enter select at least one taxonomy value for the post types that have this taxonomy
2. Single Selection Only: Each post type may only be associated with a single taxonomy value.

For (2) it would make sense to automatically change the selection box in the post edit screen to single select drop-down.

**Comment by remcokalf** [comment]
+1 for these two feature request. Could use both.

**Comment by Quasar-wpg** [comment]
I was just looking for these options while setting up new taxonomies today.

**Comment by JoshWobbles** [comment]
Did this ever get implemented?

**Comment by jimtrue** [comment]
Remember this is WP Core default behavior. There are plugins to override it. Until WP provides a method to do this in their registration of taxonomy, there's no reason for Pods to be responsible for this. Take the issue up with WP Make, not Pods.

**Comment by jimtrue** [comment]
Or Vote above @JoshWobbles and @Quasar-wpg . We won't research doing this without votes.

**Comment by JoshWobbles** [comment]
I see, I thought a single select taxonomy was already possibly in WPs core behavior.

I worked around this however by creating a relationship field set to single drop-down that just pointed to the taxonomy. same effect with the only drawback of now the control is regulated to the custom fields section instead of the sidebar panel.
