### ISSUE TITLE
"where" clause fails in shortcode

### ISSUE THREAD

**Issue by lbloom53** [pods-framework/pods#1638]
I entered this in the 2.x general questions forum, but realize after more work that this really isn't working as it should...

I’m using Pods 2.3.9. I have created a ‘song’ pod for my chorus. The pod has a ‘season’ field. I’m using a shortcode on a page and attempt to insert a where clause on season as follows:

[pods name="song" orderby="title" where="season='2013-2014'" template="SongsTemplate"]

In response, I get the following error:

Database Error; SQL: SELECT DISTINCT t.\* FROM wp_posts AS t WHERE ( ( season=’2013-2014′ ) AND ( t.post_type = “song” ) ) ORDER BY t.post_title ASC, t.menu_order, t.post_title, t.post_date LIMIT 0, 15; Response: Unknown column ‘season’ in ‘where clause’

When I omit the where clause, everything runs fine and the season display correctly on my page.

I see that ‘season’ is a meta_key in wp_postmeta, not wp_posts as in the query, but I don’t know how to reference the field correctly. Then, once I do, the meta_value is an index to a slug in wp_terms.

It seems like Pods should handle this for the where clause, just as for the query generated by the shortcode without the ‘where’ clause.

What am I missing.

Thanks,
lloyd

**Comment by jimtrue** [comment]
Considering this is from 5 years ago and was closed, yes, we have to assume this is no longer an issue. Unfortunately this particular ticket reads like a support issue and isn't specific enough as to what the exact issue is. 

So, if you can specify how you have the exact same issue (magic tag or where clause bug), @dwthomson, I can tell you if it's fixed or not or what you might be referencing incorrectly.

**Comment by dwthomson** [comment]
This is what I tried last "id.company_name" = '3083'

id is the related_field_name of the gd_company post type
company_name is the relationship field I set up in the project post type

and 3083 is id of the current logged in users company_name

This does not give any errors, it just comes back with no data. 

I am setting this up in a widget, in the where clause field.

**Comment by jimtrue** [comment]
The `{@user.company_name}` requires the Special Magic Tags configuration added to your wp-config.php in order to return a value in your where clause.  https://pods.io/docs/build/special-magic-tags/

If the company name is from a relationship field into your geodirectory post type, is it the post_title or it's own custom meta inside that post type? Because if it's the former, it's relationship_field.post_title, otherwise it's relationship_field.company_name.meta_value.  Likewise, if you're trying to map to a relationship field into users that points to the company, you want to do the same traversal in your magic tag ie, `{@user.relationship_field.field_from_related_table}`

Typically if you're matching items that are both relationships to the same table, you're better off using ID instead of trying to match text, ie, user.company_name.ID 

If you can give us the actual shortcode you're using and the SQL error, we can help you troubleshoot more easily.

**Comment by jimtrue** [comment]
For that example you just provided, what pod are you querying with that id.company_name? Because that would be traversing two relationship fields with that structure, id (which you can't use that field name since ID is the post ID and is already used), and from that relationship field into company_name and then into another field in projects.

When you go your where clause into relationship fields for matching, it's 1) relationship field in this post type 2) then field in the related post type. 

Since company_name is a relationship field, you still need the name of the field in gd_company you are matching 3083 against

**Comment by dwthomson** [comment]
Thanks for the feedback Jim.

Below is my shortcode and the SQL error.

Just to confirm again what I am trying to do:

Custom Post Type = cpt_projects (created in PODS)
Custom post type = gd_companies (created via GEODirectory plugin)
Relationship Field =  cpt_projects.company_name => gd_companies.ID
Relationship Field = user.company_name => gd_companies.ID

I am trying to display all projects which belong to the same company_name as the logged in user.

Note that I call it company_name, but it is actually the id, e.g. 3083

[pods name="cpt_projects" template="Projects Multiple" where="id.company_name.meta_value = '3083' "]

Database Error; SQL: SELECT DISTINCT `t`.* FROM `wp_posts` AS `t` LEFT JOIN `wp_postmeta` AS `id` ON `id`.`meta_key` = 'id' AND `id`.`post_id` = `t`.`ID` LEFT JOIN `wp_podsrel` AS `rel_id_company_name` ON `rel_id_company_name`.`field_id` = 3165 AND `rel_id_company_name`.`item_id` = `id`.`post_id` LEFT JOIN `wp_posts` AS `id_company_name` ON `id_company_name`.`ID` = `rel_id_company_name`.`related_item_id` LEFT JOIN `wp_postmeta` AS `id_company_name_meta_value` ON `id_company_name_meta_value`.`meta_key` = 'meta_value' AND `id_company_name_meta_value`.`post_id` = `id_company_name`.`ID` WHERE ( ( `id_company_name`.`meta_value` = '3083' ) AND ( `t`.`post_type` = "cpt_projects" ) AND ( `t`.`post_status` IN ( "publish" ) ) ) ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date` LIMIT 0, 15; Response: Unknown column 'id_company_name.meta_value' in 'where clause'

**Comment by jimtrue** [comment]
Since you're querying cpt_projects, the field you're traversing over to `gd_companies` with is `company_name` The correct traversal order is:

`relationship_field_THIS_pod.field_you_need_RELATED_pod` (tack on a .meta_value if it's custom meta).

so your error is in putting `id` in front of `company_name`; it should be:

`company_name.ID` if (3083 is in the `ID` field, post ID of `gd_companies` There would be no meta_value if this is one of the wp_posts fields in gd_companies, only if you're querying wp_post_meta against gd_companies.

so, corrected shortcode:

`[pods name="cpt_projects" where="company_name.ID = '3083'" template="Projects Multiple"]`

**Comment by jimtrue** [comment]
@dwthomson Thanks so much. Hardly magic, just most of our stuff you have to understand context (where you're starting) and traversal (where you're going). Once you get those down, you'll be doing this like a champ.

**Comment by dwthomson** [comment]
Hi @jimtrue , should the following work in a field default value?

{@user.company_name}

The field belongs in my projects table, but I want to set the company name in a dropdown to that of the logged in user.

**Comment by jimtrue** [comment]
it wouldn't be the `{@user.compan_name}`, it would be `{@user.company_name.ID}` since that's a relationship field.

BTW, please don't continue using the bug report as a support ticket. It's closed. We have well established support channels:

https://wordpress.org/support/plugin/pods/ forum tickets
or our Slack Chat at https://pods.io/chat/

This is primarily used for actual bug reports or feature requests.

Thanks!

**Comment by dwthomson** [comment]
Thanks Jim, sorry about that, i'll follow protocol going forward :)

BTW, it worked, thank you!
