### ISSUE TITLE
Any complete documentations and easy class helpers for plugin developers ?

### ISSUE THREAD

**Issue by astroneo** [pods-framework/pods#1652]
Hello and thanks for your great tool for wordpress.
Looking for a complete documentations for plugin developers who want to use pods framework as a class helpers library only 
and looking too for some  easy class helpers for coding only inside my own plugin.

**Comment by GaryJones** [comment]
@astroneo Pods now does have Composer and [Packagist support](https://packagist.org/packages/pods-framework/pods) (though it's marked as Abandoned for some reason. That would allow you to pull the code in.

Right now, there's no guarantee that classes are sufficiently isolated that you could pick one to use and not actually require most of the PHP in the plugin being loaded up as a dependency.

Since it's been a little while since the last discussion, I'll close this out for now.
