### ISSUE TITLE
Fields being overwritten with Polylang Plugin

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1851]
A user in [this support forum thread](http://pods.io/forums/topic/problem-with-polylang/) reports the following issue using using Polylang with Pods:

"I have Polylang working with 3 different language without problems with post and pages translations.
I create a new pod (page) with the title, the text and 4 fields Wysiwyg and activate Polylang."

WordPress 3.7.1, Polylang 1.1.6 and Pods 2.3.18.

**Comment by JoryHogeveen** [comment]
From what I read here it's about syncing metadata between translations (for WPML and Polylang).

Though I have started with a sync plugin for media (attachments), this functionality isn't very easy to implement for all types since you're also dealing with possible non-existend translations etc.

https://github.com/JoryHogeveen/pods-polylang-sync-meta

This plugin currently only syncs **attachments** and automatically adds translations if they don't exist.

If anyone want's to help in creating this functionality for all relationship types, please let me know!

**Comment by quasel** [comment]
@JoryHogeveen maybe make a master list of i18n issues? to see what's open or triage that stuff? so may unresolved issues around that… and all the plugins have advanced in the last year++ ;)

**Comment by JoryHogeveen** [comment]
> and all the plugins have advanced in the last year

This still isn't related to syncing relational data. i18n plugins will never support this since it's not a feature from WP. That is why I started with an addon for Pods. If you use ACF for example you will need a different tool/plugin to sync any relational data.
