### ISSUE TITLE
Optimizing multiple-relationship loop with many items

### ISSUE THREAD

**Issue by ekandreas** [pods-framework/pods#1911]
In our project we have 28 advanced custom tables with Pods as database tables.
The relations between them are not so many but still the podsrel is about 700k rows big and slows everything down så that it is not possible to use the application.
Where to start? 

_edited to add the below by: @sc0ttkclark_

Before:
- find() retrieves 846 items
- fetch() loop outputs fields from item including 5 relationship fields
- 4200+ potential select statements

After optimization by @pglewis:
- find() retrieves 846 items, using an optimized 'select' parameter for the 5 relationship fields needed in loop
- fetch() loop outputs fields from item including 5 relationship fields based on the 'select' aliases from the optimized find() query

**Comment by lougreenwood** [comment]
I'm trying to confirm that I'm using select correctly...

As far as I understand, if I do a Pods find and only select specific fields, then other fields which are not included in the select should not be addressable using display(), field(), raw() etc, is that correct?

e.g, if I do `someRelationField.d.someFieldInRelatedPod as something`, then `$mypod->display( 'something' )` should work, but `$mypod->display( 'someOtherNonSelectedField' )` shouldn't return anything, right?

**Comment by pglewis** [comment]
I might be able to help better if you give an example of what you're trying to accomplish.  The answer can be somewhat context dependent, if you select `t.*`and `someOtherNonSelectedField` is a relationship field in the Pod, then Pods will query to retrieve the title field for the relationship.

**Comment by lougreenwood** [comment]
I'm trying to figure out whether select is working as expected, I'm not seeing the performance benefits I expected. My current query is checking the values of around 15 fields, some of which reside in various related pods. It's a particularly intensive find, and at the moment is causing me major performance issues.

My assumption is that when I select specific columns for a find, fields excluded from the select (fields which are a part of the current pod) will not be accessible via display(), field() etc - e.g, I would only be able to display data from the columns I selected. Assuming this is the case, then display('fieldIncludedInSelect') would work, but display('fieldExcludedFromSelect') would not return anything.

Is this an accurate way of understanding the effect of select working as expected?

If not, beyond profiling, how can I verify that select is working as expected?

**Comment by pglewis** [comment]
The optimization is not specifically because you are using a `SELECT`, the optimization is that you include all related fields from other related Pods in the select statement as aliases and then refer to those aliased fields by the alias name in `field()` or `display()`.  

Normally, Pods does not select those related fields by default and will just go look up their values at the time you request them via `field()`.  That means an extra query for every field that must do this.  It isn't normally a big deal because you don't normally need to pull a lot of rows or fields for display per page load, but there are exceptions.  The "select trick" in this thread works around this problem by including all the related fields you may need access to in the original query, thus avoiding more DB overhead inside your loop.  

If you look at the concrete example and compare it to the gist in the thread it might make more sense.

**Comment by lougreenwood** [comment]
Ok, I think I've mis-understood the use of select...

I thought that select limited Pods from loading all the fields in a pod (or related pod) unless they were explicitly requested in select, e.g if podA is linked to podB and podsC, loading podA via pods->find will also load all fields for podB and podC?

**Comment by pglewis** [comment]
> My current query is checking the values of around 15 fields, some of which reside in various related pods. It's a particularly intensive find, and at the moment is causing me major performance issues.

If I understand: this is what we're out to solve.  Optimization works best by finding the exact bottlenecks for your case.  So let's start with the code you're running that is causing performance issues.
