### ISSUE TITLE
.vcf file type not working for file uploader custom extension limit in additional field options

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1951]
.vcf file type not working for file uploader custom extension limit in additional field options

**Comment by pglewis** [comment]
As a note to avoid future confusion: failure of .vcf is a different cause.  The vcard mime type is not whitelisted and therefore will not be allowed without adding it to the allowed list of mime types: https://codex.wordpress.org/Plugin_API/Filter_Reference/upload_mimes

#2031 was dealing with whitelisted mime types (pdf, jpg) that were not working due to a bug.
