### ISSUE TITLE
Archive page not working

### ISSUE THREAD

**Issue by steve-acet** [pods-framework/pods#1959]
EDIT WITH WORKAROUND (by @shelob9 May 22, 2014) A work around for this issue is either to resave permalinks or to turning off rewrite pages, save the Pod and turn them back on. The underlying issue remains unresolved and probably means we are not flushing rewrite rules properly.
END EDIT

I have created a basic custom post type, its the same as a normal post type. I have enabled it to have an archive, but the archive page always returns a 404. I have created a template file based on archive.php called archive-blog.php, as blog is the custom post type.

I am trying to do everything using wordpress templates, and the single-blog.php works fine, so not sure why the archive-blog.php isn't working.

Cheers,

Steve

**Comment by StaggerLeee** [comment]
I just had this problem. Difficult to solve because Pods permalinks flush doesnt work allways. Sometime it needs to be flushed from WP side. And if someone manage to click somewhere on front meanwhile you flush everything, Pods related, it goes in evil circle.
My problem was not error 404, except when i played to much with rewrite, but archive.php was active all the time, not my archive-mypodstype.php.

Maybe to be on safe side better to solve it for all time with taxonomy-mypodsmaintaxonomy.php. Just copy archive-php content to new file and edit as you need.

**Comment by Shelob9** [comment]
@StaggerLeee  Is this issue happeing with no other plugins and the default theme?

**Comment by StaggerLeee** [comment]
Ooo man, give me few days to settle with my project and test it properly.

Last night i tried it with Plugin Organizer and Safe Mode plugins and ruined my widgets, including hours of my work. Custom Pods templates inside widgets. Lucky me, mysql database have this old junk, some kind revisions from widgets. I restored website (need to fix widgets new IDs in css now) but need now to make backup and do it more peacefully.

**Comment by StaggerLeee** [comment]
Good lesson for the future, put all templates in Pods settings then call them in widgets.

**Comment by jimtrue** [comment]
@steve-acet Are you still experiencing this particular issue now that we are in 2.7.12? We are closing this ticket as we've had multiple changes with Pods Templates and Archives since this point and I've never heard of this one since this was created.

If you're still having this issue, please comment.
