### ISSUE TITLE
Add Unique functionality for meta-based Pod fields

### ISSUE THREAD

**Issue by gigi-budrio** [pods-framework/pods#1993]
Hi,

i never note this untill i need it.. :)

i think overall at plaintext or plainnumber field type, where a user can insert textual values.
it seems there isn't a way to force that the inserted values are UNIQUE. I find it so useful, if i want all different values.

Do you think it's useful..??
Do you think you can implement ?

THANKS..!!

**Comment by jimtrue** [comment]
Isn't this **really** a business logic type of function (since the rules of uniqueness are so disparate depending on business logic). ie, one case might want email address to be unique, one might want name to be unique. This is enforcing us to add a pre_save filter that would check the dataset against this field in the current pod to make sure it's unique, when this would seem to be something the developer could add in their code based on their business logic needs.

A better solution would be an auto-incrementing counter field that's unique (which is what most people are looking for), or perhaps a new interface wrapped around unique that would also include customized messages for records that aren't unique.

Seemingly related to #1297 as well.
