### ISSUE TITLE
Support WPML translation for "Settings" post types

### ISSUE THREAD

**Issue by jeremyeast** [pods-framework/pods#2017]
Would be amazing to have WPML integration for "Settings" Post Types.

Custom Post Types are already compatible, but they are not practical for some site architectures.

**Comment by JoryHogeveen** [comment]
Not sure if this will be possible since settings pages aren't translatable objects to i18n plugins.
Settings pages are meant for global settings (not visible in the front-end).
Sounds like a cool feature though...

If these pages should be compatible with i18n plugins then the whole structure of these pages should be changed to something similar as post types. Also, these "custom" setting pages should be registered (and stored in the dattabase) as post types.
_(Guess this would mean that the storage type for such a settings page would be "Meta" in Pods terms.)_

I noticed that there is a option "Admin UI Style" that lets you select "Post Type UI" But I don't see any changes. Was this a start for a function like this?

@sc0ttkclark @pglewis Any thoughts?
