### ISSUE TITLE
Codepress Admin Columns doesn't see Pods' table-based custom fields (meta keys)

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#2400]
An older version of Codepress Admin Columns (1.4.9) appears to recognize table-based custom fields added by Pods.  Integration broke somewhere.

**Comment by tommyd3mdi** [comment]
I'm still on Pods 2.5 and while this bug is still open (and the milestone is set to 3.0) the above patch ebecfba seem to have made it already into this very version of the Pods framework - at least I can see it in my installation.

I'm reporting this obviously because custom fields are (again?) not visible even with this change. I am using codepress' admin columns 2.3.2.

**Comment by pglewis** [comment]
This is "can't reproduce" for me at the moment.  The user interface is not 100% intuitive for custom fields, but the following works for me in testing with both table and meta based storage on a custom post type: 

* Click "Add Column"
* For "Type", choose "Custom Field" in the "Custom" section

Selecting "Custom Field" will modify the UI and provide a new drop down for the actual custom fields.  

I'm going to punt this from 2.5.2 for now, let me know if this is still an issue and if there is something different I need to do to reproduce the problem.

**Comment by Ramoonus** [comment]
@markoheijnen

**Comment by pglewis** [comment]
Closing this since we've not been able to get any information to reproduce it.
