### ISSUE TITLE
Adjust caching in get_table_info

### ISSUE THREAD

**Issue by jamesgol** [pods-framework/pods#2533]
'pods_api_get_table_info_default_post_status' should be run at least once per instance of pods.  Need to move where the caching happens.  Just cache the expensive operations and let the other stuff happen on every call

**Comment by sc0ttkclark** [comment]
`pods_api_get_table_info_default_post_status` doesn't get run on cached values, and some cases where it caches the default, and the filter doesn't run again. This is a problem when upgrading Pods sometimes.

Further, when previewing a post, this becomes problematic because the table info doesn't store an alternative for when previewing (which should include everything that the `pods_api_get_table_info_default_post_status` filter includes PLUS 'future'.

**Comment by sc0ttkclark** [comment]
Closing this and opening a new issue
