### ISSUE TITLE
avatar field / get_avatar should square-crop the image used

### ISSUE THREAD

**Issue by cheekyboots** [pods-framework/pods#2738]
Hi,
I defined an avatar field for Users. The image size that get_avatar returns is not square if the original is not square. Expected behavior would be to automatically crop any uploaded image to be square.  (Since gravatars are always square and the places avatars are used in the admin forces a square image, so the current not-a-square images get distorted).
Emma

**Comment by JoryHogeveen** [comment]
Not sure but looking at the code this seems to be fixed.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
This is an old one and I believe rendered avatars are always cropped to a square when using any Pods related function.
Of course, the original images and sizes are untouched since these are regular media items.

https://github.com/pods-framework/pods/blob/8f5a4e8cb226af94c0f3d8cb3c7f90b2ba85bb43/classes/fields/avatar.php#L147

I believe this issue can be closed right?

**Comment by sc0ttkclark** [comment]
If I had to make a guess, the image response from wp_get_attachment_image does not return constrained to the exact size. The absolute best option to take care of that problem is to add a [custom image size](https://developer.wordpress.org/reference/functions/add_image_size/) with that square size and it should always be able to return it. The caveat is that the image size will be generated for all images/attachments uploaded, not just avatars.

**Comment by sc0ttkclark** [comment]
I think it would be good to put together some sort of solution for this on the Pods side given the context of get_avatar and the intention of getting the square image.

**Comment by JoryHogeveen** [comment]
Agreed, but please check the code I referred to, I believe we already do this..

**Comment by sc0ttkclark** [comment]
If you look at pods_image() usage there, it's not doing the forced image resize check and the forced image resizing (if used) only checks if the size was the same as the full image, which might not be the case for small images covered by medium/thumbnail/etc. So I don't think that's enough coverage here.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 

`wp_get_attachment_image_src()` accepts an array of height and width and in turn WP will look for that specific file.
If it doesn't exist, it will return the full size.

So, if it exists, it will return that actual size, which is a square size for avatars since that is what is passed as the size parameter.
If it doesn't exist the `src` will be the same as the full size to this will trigger `pods_image_resize()` which will create that file, even if it's a custom size.

**Comment by JoryHogeveen** [comment]
Tested this locally and I can confirm this is what happens.
However, WordPress will never return an image smaller than the thumbnail size or larger than the full image size.

I will add a new PR that enhances fetching avatars for when the field name is `avatar`. This is actually more of a special magic tag.
