### ISSUE TITLE
Improper return values from number fields

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2777]
TMy test is as follows:

```
     var_dump( get_post_meta( 85, 'bool', true ));
     var_dump( pods('article',85)->field( 'bool') );
```

Result with unchecked is an empty string from `get_post_meta()` and NULL from `Pods::field()`, with checked I get 1 from from `get_post_meta()` and NULL from `Pods::field()`

The user who was reporting this issue to me on FB, when I asked them to var_dump() the field reported "I'm getting various results when it should really be one of two, since it's yes/no... string '' (length=0) , string '1' (length=1) , string 'Array' (length=5)" then said it was working fine.

Something odd is up here. Both of us testing with latest 2.x

**Comment by torlowski** [comment]
FWIW, I realized that the string 'Array' (length=5)" results are only showing up for users that this field (now a radio button, previously a checkbox) hasn't been updated since changing it to a radio button. Once I resaved the values, that result has gone away.

**Comment by pglewis** [comment]
I assume this is a Boolean field from the example code, and not number as in the title?  

I get consistent results here:
* custom post type named 'article'
* a single Yes/No field named 'bool' with default values

Using the same code Josh supplied except for post ID:  When checked, I get the string '1' from both cases.  Unchecked I get the empty string from `get_post_meta()` and the string '0' from Pods.  

This all seems reasonable since WordPress isn't aware of Pods' field datatypes.  Am I missing something in my configuration?

**Comment by pglewis** [comment]
I've tried to recreate it multiple ways including changing from checkbox to radio buttons.  Feel free to re-open if it creeps up again and we can reproduce it.
