### ISSUE TITLE
Revisit ! is_network_admin() check in PodsInit

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2803]
See: https://github.com/pods-framework/pods/issues/825#issuecomment-56620588
See: https://wordpress.org/support/topic/multisite-crash-update-24?replies=15#post-6711603

#825

**Comment by JoryHogeveen** [comment]
I keep having this issue on some networks and I think I found why.

This only happens when Pods is activated in the complete network by default.
I'm not sure why, but Pods gets fully loaded in the network pages with this setting and creates a fatal error because PodsInit is not found (because of "!is_network_admin").

I think the "!is_network_admin" check needs to be done way sooner so Pods doesn't initiate in the network pages because the pods_no_conflict_check still calls the PodsInit class.

Or the other sollution (my current sollution) is to allways load PodsInit...

**Comment by JoryHogeveen** [comment]
I keep getting this error on a network. Somehow the pods_init() is required. For me it's a small issue because at every update I can simply change the init.php file, but just thought I'd let you know!

**Comment by JoryHogeveen** [comment]
Why is this labled as "Backward Compatibility"?

It happens when Pods is activated for the whole network.
PHP versions from 5.3 up untill 7 -> WP versions 3.8 up until 4.5 -> and Pods versions for as long a I use it all produce the same error.

**Comment by JoryHogeveen** [comment]
Fixed in https://github.com/pods-framework/pods/pull/3665
