### ISSUE TITLE
How to code '$pod->fetch()' for "Fatal error: Can't use method return value in write context in ..."

### ISSUE THREAD

**Issue by cannect** [pods-framework/pods#2816]
Hi,

I came across a strange error today. I usually do something like:

```
$pod = pods('pod');
// etc

// Then:

while($pod->fetch()){
// do stuff here
}
```

However now I get this error: `Fatal error: Can't use method return value in write context in ...` If I look around (http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context), it is caused by that PHP cannot handle the reference value.

Now I am on a cPanel environment which I manage. Can I change something in PHP to overcome this error?

**Comment by Shelob9** [comment]
@cannect -

I can't say for sure, since I can't debug directly. What I assume is happening is that $pod is not a proper object, so it is being evaluated in write context and since you are on an outdated version of PHP you get an error. I would check that $pod is a proper Pods object, I bet it is not.

**Comment by cannect** [comment]
Hi thank you,

You are right, I used it in my own class as follows:

``` 
class Property {
    protected $currentProperty;

	public function init(){

		$pod = pods('property')->find(array('where' => "..."));

		while($pod->fetch()){ // Fatal error happens here
			$this->currentProperty = $pod;
		}
	}
}

```

I am on PHP version 5.4.37. I can't see why it is wrong to assign the current property I am working on to currentProperty?

**Comment by cannect** [comment]
I made a mistake. It is not on that line above, but on another file. So it is all about the currentProperty variable who I may not access directly in combination with a empty() expression.

Like this:
```
$currentProperty = $this->currentProperty;
if(!empty($this->field('field'))) { // Fatal error here
}
```

**Comment by sc0ttkclark** [comment]
Yeah this is a limitation of PHP empty() which supports what you're trying to do in either php 5.5 or maybe it's the next major release

**Comment by sc0ttkclark** [comment]
Just following up on one of your comments, this would be proper setup/find usage for a Pods object:

`$pod = pods('property', array('where' => "..."));`

Doing a ->find() will return a non-object, so we have a way to run find() right away which happens when you pass an array into the pods() second parameter.

**Comment by Shelob9** [comment]
@cannect I'm glad you got this sorted out. I'd recommend upgrading to 5.6 so you don't have to worry about this sort of deficiency in the language.

I can't wait until September, when I can start arguing that we stop supporting 5.4:)

**Comment by cannect** [comment]
Scott and Josh, thank you very much. Also a great tip to use find directly!
