### ISSUE TITLE
Pods::find() when use to get associate taxonomy terms only gets first term

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2915]

**Comment by jimtrue** [comment]
Adding commentary from #3018 

Each Tag Traversal does not work with Taxonomy - Needs some love. submitted via Slack by jimtrue

Related to Forum Post:
http://pods.io/forums/topic/template-each-spits-unexpected-results-on-taxonomy-rel/

This is related to SEVERAL support forum posts, but basically:

[each] tag traversal doesn't work with Taxonomy at all. Obviously listing {@taxonomy} does a display array list which is fine, but doesn't give people what they're looking for: links to the taxonomy pages.
As a workaround, people have attempted to create relationship fields to Custom Taxonomy and traversing that with the [each] tag. That actually returns a matching entry for EVERY taxonomy term for the number of actual selected taxonomy terms.

My suggestion is we treat Taxonomy as a different animal and treat it differently, either give it it's own style of output tag for traversal or make the each tag recognize that it's traversing a taxonomy.

This is tied to the root cause of Pods::Find() only returning one term on associated taxonomy.

**Comment by pglewis** [comment]
I have not been able to reproduce this issue via the built-in post and category: 

```
<pre>
    <?php
    $params = array( 't.ID = 20' );
    $the_pod = pods( 'post', $params );
    var_dump( $the_pod->field( 'category' ) );
    ?>
</pre>
```

nor with as custom post type and taxonomy: 

```
<pre>
    <?php
    $params = array( 't.ID = 254' );
    $the_pod = pods( 'multitermpost', $params );
    var_dump( $the_pod->field( 'multitermtax' ) );
    ?>
</pre>
```

Both those tests correctly show an array with all terms associated to the target post.
