### ISSUE TITLE
Template error notification won't go away, no advanced tab in Pod option

### ISSUE THREAD

**Issue by m-fox** [pods-framework/pods#3247]
Keymaster Jim in the Pods forum asked me to post this here.

I have a couple of custom post types that are hardcoded in a plugin.
I’m using Pods to extend the custom post types.
They both have ‘has_archive’ => true, in the setup.
I’ve created templates for the post types to change the layout. The templates work with the single posts but not the archives.

On the page to Edit Pods I get an error:

>The Pods post type Quotes has an archive template set to be displayed using Pods auto template, but the Pod does not have an archive. You can enable post type archives in the “Advanced Options” tab.

There is NO Advanced Options tab anywhere in the Edit Pod option.
Is there a way to get the advanced tab when we’re extending an existing custom post type?

I can edit the pod without any issues. The error notification stays and doesn't go away.

I'm running a Genesis theme and also noticed when I do use an archive template it doesn't display the template format. I have to create an archive-posttype.php and code the layout there, instead of using the template (I'd prefer to use the template).

Thanks.
The original issue was reported in the Pods forum here: http://pods.io/forums/topic/template-error-wont-go-away-no-advanced-tab-in-pod-option/#post-192962

**Comment by jimtrue** [comment]
Check to see if you still don't get the Archive template to show on a default theme like Twenty Fifteen. Genesis requires some modification to get Archive Templates to show. Do you still have access to Auto Templates selection within your Extended Pod?

**Comment by m-fox** [comment]
It's still there with 2015.
I also have the 'genesis-cpt-archives-settings' in the custom post type 'supports.'
What would be nice is in the Auto Template Options, there was a 'none' or 'default theme view' option in the Archive view template and the Single item view template. We shouldn't have to use a template. For one of my custom post types I only want it on the single item view and not the Archive view.

**Comment by jimtrue** [comment]
That wasn't actually the question: I asked if the archive 'worked' when you shifted it to Twenty Fifteen? As I indicated, the Genesis themes because of their extensive action hooks, don't always work as expected with the auto archive templates. Sometimes you have to 'unhook' a lot of those settings. the 'genesis-cpt-archives-settings' hasn't really made much difference for me when I was working on the archive setting with Auto Archives.

As to the none or default theme view option, there's an issue out there for that one already, #3142 and #3148 (the patch to do that).

**Comment by m-fox** [comment]
My apologies. I misread.
Yes! With 2015 it displays properly.

I've noticed if I change Genesis theme settings for the content archives to "Display Post Content" it works fine. And would solve the issue in Genesis.

However, I want "Display Post Excerpts" on the blog, category, and other taxonomy pages. But not on this post type.

I'll submit a request to StudioPress on how to do this. Screwing around with the loop in Genesis is beyond my coding knowledge.

**Comment by jimtrue** [comment]
Believe me, I feel your pain. Genesis is of the most complicated 'easy themes' out there to configure. I don't like having to dig into action hooks & filters just to modify how WordPress normally does things.

If you snag the http://pods.io/latest/ it includes the patch above that allow you to not select a Pods template (so it'll behave as normal). I'm going to go ahead and close this since this is being patched with #3148 and otherwise is just a theme issue.
