### ISSUE TITLE
ID is not numeric

### ISSUE THREAD

**Issue by nitin41** [pods-framework/pods#3290]
Hello,

I'm getting "ID is not numeric" message when i'm going to create new post of any custom post.
What should i have to do to solve this problem?
Please asap it's vary urgent.

Thanks

![image](https://cloud.githubusercontent.com/assets/10435077/11866191/6e78a680-a4cf-11e5-8362-d301074549d5.png)

**Comment by pglewis** [comment]
I suspect this may not directly be a Pods issue because we've had a few thousand downloads/updates this week alone and I haven't heard this reported at all.  

Unfortunately the screen shot really doesn't give us anything to go on as far as trying to reproduce the problem.  Since you're paying for managed hosting I suggest contacting WPEngine and see if they can help you diagnose what is wrong.  If it turns out to be due to Pods, they can probably help provide more information for use to track it down.

**Comment by nitin41** [comment]
Thanks @pglewis

**Comment by jimtrue** [comment]
If you can, also provide us anything from your Pods Admin, Settings, Debug listing and provide it here.

**Comment by nitin41** [comment]
Thanks @jimtrue

**Comment by jimtrue** [comment]
Do you have any update @nitin41 ?

**Comment by jimtrue** [comment]
@nitin41 We've not heard any further input from you on this issue though above you considered it 'needed help asap'. 

Since we've heard no further details from you, we're assuming you were able to get it resolved and it had nothing to do with our plugin.

**Comment by T-A-G** [comment]
Hi. I'm having the same problem.

**Comment by quasel** [comment]
@T-A-G 
did you read the thread? 
did you try the suggested steps? 
do you have any further information for us?

**Comment by T-A-G** [comment]
Hi,

I did deactivate the plugins but forgot to change the theme to a twenty twelve which i have done now. It now seems to be working so I'm guessing it doesn't have to do with pods. thanks for the help.

**Comment by quasel** [comment]
You're welcome! The best way to say thanks is to leave a 5 star review at https://wordpress.org/plugins/pods/ ​*and*​ (if you're feeling especially generous) become a Friend of Pods at https://pods.io/friends-of-pods/
