### ISSUE TITLE
Flexible Relationships - 'Add New' items from input field

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#3309]
Flexible Relationships is a new feature that allows you to add new items directly from the form you're in, for a relationship field using a new modal workflow.

![add-new](https://cloud.githubusercontent.com/assets/709662/11681696/14bf7cea-9e26-11e5-8a7a-a646fcb4a288.png)
## Remaining tweaks
- [x] CSS: Hide Terms list in modal `body.edit-tags-php #col-right { display: none; }` @nicdford 
- [x] CSS: Make Term form full width `body.edit-tags-php #col-left { width: 100%; }` @nicdford 
- [x] CSS: Add margin / padding to modal forms @nicdford 
- [x] classes/PodsForm.php tweak: Set modal title `data-modal-title="..."` @pglewis 
- [x] classes/PodsForm.php tweak: Check permissions for user to 'Add New' of each object before outputting add new link @pglewis

**Comment by UchihaCFC** [comment]
what branch has worked the latest on this? what is missing? since I see several issues about it and would like to help finish it, and would need something like that for a project I'm doing. But I'm making a mess with the branches !. Thank you! ;)

**Comment by sc0ttkclark** [comment]
@nicdford can you take a look at your schedule and see when you might want to put some time into the CSS on the items here?

**Comment by sc0ttkclark** [comment]
@UchihaCFC this is all on `release/2.7` right now.

**Comment by nicdford** [comment]
@sc0ttkclark I'll put it on my plate for this weekend

**Comment by sc0ttkclark** [comment]
Bon Appétit!

**Comment by nicdford** [comment]
:hamburger:

**Comment by UchihaCFC** [comment]
@sc0ttkclark yohoo!! let's go to try! thanks! 🍻

**Comment by nicdford** [comment]
@pglewis I looked into these CSS issues, but couldn't seem to figure out what I was trying to remove/adjust so I didn't create a commit for it. Scott mentioned that maybe the class names have changed since this issue was created? Or if there could be screen shots taken that indicated the issues visually, that might also help me figure out what CSS needs to get written. Let me know! I'm getting into my routine with the new job, so if you want to start relying on me more for visual changes i'm happy to help! Thanks for your patience bringing me back up to speed! 😄

**Comment by sasimon** [comment]
Is there any more work being done on this? I'm beta-testing this feature, and I noticed two things:

- The "Add New" button is there on all relationship fields, not just the ones supposed to be "flexible."
- For "flexible" relationships, the "Add New" button is ALL that's there.

Also:
Closing the modal window should trigger an AJAX call to refresh the main select item. As it stands, I cannot mark Relationship items required because they must be first saved as drafts before I can add the new items as selected on the parent.

**Comment by pglewis** [comment]
Yes, "Add New" will be an option for all relationship fields regardless of the view used.  

Refreshing the list after closing the modal is the primary remaining piece for 2.7.

**Comment by sc0ttkclark** [comment]
@pglewis is the tasklist on this issue still valid or do we just add the one item for 'Send data from form submit to parent page from modal'?

**Comment by pglewis** [comment]
I had the same question.  I've marked all the items finished as I believe we're just waiting on the actual functionality for this task.

**Comment by pglewis** [comment]
@sc0ttkclark: You might want to consider this closed and start a new fresh issue, without any confusing history, for what's left.
