### ISSUE TITLE
Empty required file generating problem

### ISSUE THREAD

**Issue by seifeddineSymane** [pods-framework/pods#3319]
Hello,
first of all, i would thank you for this magnificent plugin!
i found a critical problem, when adding a new post with a field type "File" and required; if i let the file empty the form is submitted and generate an error "fichier est vide" (empty file) but the problem that the post has been added to the list without a file.
i suggest to do the test in client side with jav
![Uploading Capture d’écran 2015-12-28 à 16.50.39.png…]()
ascript to force user adding a file.

**Comment by Ramoonus** [comment]
Hello @seifeddineSymane could you please include the screenshot?

**Comment by sc0ttkclark** [comment]
Sounds like the workflow is:

1. Start new post
2. Submit form without adding file (field is required)
3. Item processes, file is not added

This sounds like a Post Type, in the 'New Post' screen. We have multiple issues on JS Validation for the post and other WP screens for the same reason -- our current way isn't all that great.

It's not a bug necessarily though -- it's a needed enhancement. I'm not saying it's working the way it should and that's why it's not a bug, but it's working as it was initially built to -- we had to save time and we never came back around to add the JS validation that would make things better.

**Comment by seifeddineSymane** [comment]
it's certainly a **bug** not an enhancement => showing an error and adding the element? it's conflicting!

**Comment by sc0ttkclark** [comment]
We can't show an error in PHP before WP inserts the post because our saving routine runs after the post is created so we can use the Post ID for relationships / file fields, or table-based Post Types where we add a row to the table with the same ID to match.

We've got an issue open for JS validation we'll follow up on though, I definitely want to get this added as you're right, it's conflicting for normal workflows. #2424
