### ISSUE TITLE
[Fatal error] PodsInit wp 4.4.* multi and pods 2.6

### ISSUE THREAD

**Issue by global01** [pods-framework/pods#3353]
I’m using **PHP 5.6.14-0+deb8 et Wordpress 4.4.1 in Multi and updated Pods to 2.6 via wp-cli**.
I now have this Fatal error (and blank pages) when I click on one of the links to administrate the multisite section /wp-admin/network/:
`
[error] 40116#0: *488544 FastCGI sent in stderr: "PHP message: PHP Fatal error: Class 'PodsInit' not found in /srv/prod/mgt-prod/wp-content/plugins/pods/includes/general.php on line 1789" while reading response header from upstream, client: xx.xx.xx.xx, server: www.xxxx.com, request: "GET /wp-admin/network/update-core.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.xxxx.com", referrer: "http://www.xxxx.com/wp-admin/"
`
I removed the plugin and did directly a wget on your latest version and the problem still appears, on my dev as well, I double checked the statics variables wich seems ok and the PodsInit Class obviously exists.

If you can help me,

Thx

**Comment by pglewis** [comment]
Possibly related: #2803

**Comment by jimtrue** [comment]
I sent this one over from the forums because it sounded familiar. Is there a workaround, possibly?

**Comment by JoryHogeveen** [comment]
The workaround is this:

(line 81 - 88 in init.php)
`
	        if ( false !== pods_compatibility_check() ) {
			$pods_form = pods_form();
			$pods_init = pods_init();
		        /*if ( ! is_network_admin() ) {
		        }*/
	        }
`

If i'm not mistaken there is no need to do a is_network_admin() check since the plugin needs to be activated in the whole network in order to be loaded at all when on a network page.

Shall I make a patch?

See also: https://github.com/pods-framework/pods/issues/2803 and https://github.com/pods-framework/pods/issues/825

**Comment by JoryHogeveen** [comment]
Fixed in https://github.com/pods-framework/pods/pull/3665

**Comment by redpik** [comment]
not fixed for me.
Pods 2.7.1
WP 4.9 multisite network

**Comment by global01** [comment]
Yes indeed since the last 2 versions

2017-12-15 14:19 GMT+01:00 Benjamin PONGY <notifications@github.com>:

**Comment by jimtrue** [comment]
@redpik and @global01 Did you see this fixed when @JoryHogeveen noted it fixed back in July of 2016 and this just resurfaced with 2.7 and 2.7.1?

**Comment by global01** [comment]
Yes I can't remember exactly when it was fixed but it's not working anymore
since the last 2 versions.
http://www.ma-grande-taille.com/wp-admin/network/* doen't work anymore,

I need to use the WP-CLI to update the plugins.

2017-12-15 14:33 GMT+01:00 Jim True <notifications@github.com>:

**Comment by JoryHogeveen** [comment]
@global01 @redpik 
I had the same think on some of my sites as well. The problem happens when (for example) a theme uses Pods functions globally in functions.php. `pods_field()` for example.
The theme functions.php is also loaded on the network admin pages (where PodsInit isn't loaded) so this will cause an error.
If you move the pods functions in a hook (outside the global scope) or in the theme template files the error will probably disappear.

**Comment by redpik** [comment]
same error, again and again.

WP (network) 4.9.8
Pods 2.7.9

appears in, for example:
https://www.xxxxxxxxxx.com/wp-admin/network/update-core.php

**Comment by sc0ttkclark** [comment]
Is Pods network activated or just activated on the main site?

**Comment by redpik** [comment]
Don't remember. I can't go on /network/* pages.

**Comment by redpik** [comment]
Don't remember. I can't go on /network/* pages.

**Comment by redpik** [comment]
Hi there,

Same bug, again... :-1: :-1: :-1: 

PODS 2.7.11
network activated.

**Comment by redpik** [comment]
@jimtrue @sc0ttkclark @pglewis same bug on PODS 2.7.12 (network activated)

**Comment by redpik** [comment]
up

**Comment by JoryHogeveen** [comment]
@redpik 
Could you please test this issue with my latest PR: #5395 
Thanks!
