### ISSUE TITLE
Please add support for date/time picker localization

### ISSUE THREAD

**Issue by S8nsick66** [pods-framework/pods#3429]
I find no way get the date picker/time picker in another language than English.

Translations are available though, just needs to be implemented in Pods:
https://jqueryui.com/datepicker/#localization

Pods 2.6.1
WP 4.4.1

**Comment by pierluigiabramo** [comment]
Solution? Thanks!

**Comment by jimtrue** [comment]
@pierluigiabramo no workaround as of yet; this is considered an enhancement.

**Comment by pierluigiabramo** [comment]
Thank's Jim, so expected in 2.6.x ? or ?

**Comment by jimtrue** [comment]
@pierluigiabramo you'll see that label 'needs contributor'. That means we have no one on the Core Team that can tackle that one right away and it's been out there (untranslated) since we added the DatePicker. Features/Enhancements unfortunately don't get as much weight in our current roadmap and we often have to rely on external contributors to pick up and help in those areas. We have a very specific roadmap for the next few releases which are taking extensive coding cycles. We hit the hard-hitting bugs and what's on the roadmap first and if we can get the cycles, it might go into one of the later releases. It won't be on 2.6.x or 2.7 unless we can find someone willing to jump on this one.

**Comment by JoryHogeveen** [comment]
Hi @pierluigiabramo ,

I'm busy with a l10n component for Pods and have included this enhancement. Will keep you up to date!

**Comment by JoryHogeveen** [comment]
@jimtrue @sc0ttkclark  I can also build this within the Pods core if you would prefer this. At this point I'm getting the translation data from the jquery-ui github:
https://rawgit.com/jquery/jquery-ui/master/ui/i18n/datepicker-LOCALE.js

**Comment by JoryHogeveen** [comment]
First dev for the component can be found here: https://github.com/JoryHogeveen/pods/tree/component_i18n

Based on 2.x tree. Added files:
/components/I18n/I18n.php

**Comment by JoryHogeveen** [comment]
https://make.wordpress.org/core/2016/07/06/jquery-ui-datepicker-localization-in-4-6/

**Comment by JoryHogeveen** [comment]
@sc0ttkclark: @pglewis 
This is in the i18n component (planned for 2.7) at the moment. Want to keep it there or move it to the date/time field itself? 
I'd say the field is more logical plus we can patch it over to the next minor release aswell with a check for WP 4.6.

**Comment by JoryHogeveen** [comment]
Diplicate of #1363
@sc0ttkclark same for this one.
