### ISSUE TITLE
Internal Server Error while accessing Custom Post Type over WP-Rest-API

### ISSUE THREAD

**Issue by manikmagar** [pods-framework/pods#3455]
I have a custom post type Store which I access over WP Rest API endpoint wp-json/wp/v2/store. I added few more custom fields to this post type and suddenly I started getting Internal Server Error when endpoint is called.

I saw below error in logs -
`PHP Fatal error: Call to a member function fields() on a non-object in /wp-content/plugins/pods/classes/PodsRESTHandlers.php on line 79`

After looking at the code at that line, I guessed it must be because of relationship field so I removed that field, saved the pod and access API again. **And then I get the correct response from API.**

If I add this field back to post type, it again breaks the API response.

**Field Configuration-**
Field Type: Relationship
Related To: Simple (custom defined list)
Custome Defined Options: 
CB|Cashback
SR|Store Rewards
CP|Coupon Only

Allow to read on API: Yes

On Rest API tab for this field, If I choose to "Response Type = ID Only" **then it works** but If I choose "Response Type=Full" then it doesnt.

For me, I just need ID so I am good for now, but it would be good to have full info in response.

Can someone please take a look at this?

**Comment by quasel** [comment]
The REST API (and WP API plugin) are still in beta. We cannot give these as high a priority as our existing road map. We are a free plugin with free support. But we will look into it togehter with other related issues - We unfortunately lost one developer who was helping with the REST API stuff
So that means our other developers have to get up to speed with the project.

Feel free to submit a PR if you find the issue ...

**Comment by lougreenwood** [comment]
I'm seeing the same issue, however, if we switch the response type to ID it always displays as 0.

@quasel I understand you're short on API manpower, but is there any indication that these API issues will be getting priority for Pods 2.6.3, it seems that with WP 4.5 due any time now, focus on the API from the general community will become greater.

**Comment by jimtrue** [comment]
@lougreenwood We have items that have been longer (and more requested) on the [Roadmap for Pods] (http://pods.io/2015/12/26/new-path-pods-3-0/) so while we definitely understand the urgency of the REST API project, it's not included in WP 4.5, so we can't make it an immediate priority when we're strained for programming resources as it is. As @quasel makes a good point, if you know someone who is very familiar with the REST API project and can take a look at the issue, we wholeheartedly welcome folks to submit PR's following our [Contribution Guidelines](https://github.com/pods-framework/pods/blob/master/CONTRIBUTING.md).

We're definitely not ignoring REST API, we have limited resources and we have to handle the features/enhancements and bugs that our greatest number of users are clamoring for.

**Comment by pcfreak30** [comment]
Just ran into this same issue with relationships. Will be debugging it as I for once found the project I am on a good candidate for its use.

**Comment by pcfreak30** [comment]
Didn't think I should make a PR on this since its more of a hack to correct the error and Im sure theres a better way to write it. However this got my stuff working. The prob lies in the assumption that the related pod field(0 call will return a `Pods` instance when it returns an array. Theres the case that multiple instances could be returned too. The patch has it always return an array for a pick/relationship.
[_Fix_rest_relationships.txt](https://github.com/pods-framework/pods/files/253768/_Fix_rest_relationships.txt)

**Comment by quasel** [comment]
I think this should be fixed - at least the quick look at code suggests it is ;)
