### ISSUE TITLE
Can't query taxonomy 

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3523]
On extended and likely non extended, this returns false.

```pods('mytax' )->data()``

this returns data

```pods('mytax', ['limit' => false])->data()```,

and this returns data

```pods('assignment_month', ['limit' => null])->data();```

Seems a `isset` check is going screwy here?

**Comment by sc0ttkclark** [comment]
'limit' has to be -1 or a positive integer. -1 equates to no limit. Using null or false was never explicitly covered in a use-case for the code, definitely stick to the rivers and streams that you used to.

**Comment by pcfreak30** [comment]
You should be able to not pass anything the same as a post type pod and just loop over (where it limits to 10 by default i believe).

**Comment by sc0ttkclark** [comment]
Right, don't pass anything and it uses defaults.

You can't call data() outright without a find() to actually pull the data. Maybe consider `->find()->data()` since pods() won't find without Paramus passed into the second argument, and it's easier to read and understand what's happening than putting an empty array into that second argument.
