### ISSUE TITLE
Standalone Pods Class

### ISSUE THREAD

**Issue by bkonia** [pods-framework/pods#3576]
Currently, when accessing Pods ACT tables from an external (non-WordPress) application, you have to use a standard MySQL library/framework, etc... This works, but it's not ideal, since Pods has its own proprietary approach to storing relationships, etc... Therefore, when looking up data in relationship fields, you have to build the SQL queries manually. The whole point of ACT's is to be able to share the database with external applications, so I think querying the data externally should be made more convenient and consistent, by abstracting away the Pods internal storage mechanism. I'd like to have a standalone version of the Pods class that can be instantiated outside of WordPress and used to access the database with the exact same code one would use within WordPress.

**Comment by sc0ttkclark** [comment]
WordPress + Pods can be included within other PHP applications, but we are working on storing relationships in the same table in some potential cases. See #3315

**Comment by sc0ttkclark** [comment]
I'm also worried about pulling out all of the Pods logic outside of WP and into it's own single class due to the huge size of the codebase that would have to fit into that class to cover all of the needs from DB abstraction to the field/display/traversal and much much more. I'm thinking this might be a "out of scope" thing to Pods itself.

**Comment by bkonia** [comment]
Yes, I understand the concern about the codebase size. However, I was thinking it would just be a small subset of the codebase, to allow the user to perform database queries. The display stuff and everything else wouldn't need to be included in this. If the user is accessing the data from an external system, we can assume that system has its own framework and display methods. This would be like a bridge between the two systems, not an entire standalone framework.

**Comment by sc0ttkclark** [comment]
I still stand by the fact that #3315 would solve all of your needs, all you'd do is just query the database with PHP. Providing an abstraction layer for this type of edge case even if it just queries a single table, seems like overkill especially since you can embed WP+Pods into another app.

Better yet, you could hook into the post-save hook for ACT's and send data to any other system or app or database you'd like.

Building this is just not going to be able to be a priority for us in the near future, but we'll see where we're at in a few years.

**Comment by bkonia** [comment]
I agree that 3315 would be fine. Do you have any ETA on that? I'm building this application now and would greatly prefer to have the joins stored in the same table, rather than using podsrel. The save hook isn't a viable solution, because the external app needs to both read and write to the Pods database.
