### ISSUE TITLE
Polylang picture pb

### ISSUE THREAD

**Issue by LajouxClement** [pods-framework/pods#3613]
The pods was create in Version 2.6.6 and then i've instal Polylang plugin

In my pods I've a field of type "File / Image / Video "

when i create the pods of the other language i fill the field 
![add pic](https://cloud.githubusercontent.com/assets/14345236/16415638/84a38b34-3d3e-11e6-80ab-be6b1f6c1e42.PNG)

but when I save the  "File / Image / Video" field is empty
![after save](https://cloud.githubusercontent.com/assets/14345236/16415674/b6e5d872-3d3e-11e6-9ebe-5d64785bb546.PNG)

And the picture is not save

**Comment by JoryHogeveen** [comment]
Hello @LajouxClement 
Did you set media to be translatable?

**Comment by LajouxClement** [comment]
Yes media was translatable I've just disabled and it works 
thanks a lot

**Comment by JoryHogeveen** [comment]
If you want to use translated media with Pods & Polylang it can be a bit of a drag, though for SEO it's awesome because of the translations for labels.

Please also keep in mind that if you set "custom fields" to sync with translatable media this wil most likely fail since it will try to sync media of an other language.

I've started with a module for this but it not even nearly done because there is a lot of implementations to fix before it will be stable.

**Comment by LajouxClement** [comment]
Ok thanks for advice
