### ISSUE TITLE
Feature Request: Toggle popular regions on taxonomy admin page

### ISSUE THREAD

**Issue by fireundubh** [pods-framework/pods#3652]
I'd like to toggle the tag cloud ("popular regions") on the taxonomy admin page (edit-tags).

See: [http://wordpress.stackexchange.com/questions/39566/how-to-remove-the-tag-cloud-from-custom-taxonomy-admin-page](http://wordpress.stackexchange.com/questions/39566/how-to-remove-the-tag-cloud-from-custom-taxonomy-admin-page)

A checkbox for this toggle could be placed on the Edit Pod page in the Admin UI tab section.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark @pglewis Shall I make a patch for this for 2.6.7? It seems like a fairly easy fix.

**Comment by sc0ttkclark** [comment]
Yeah, sounds like we need another checkbox option to disable Tag Cloud from the Term management page, since the `show_tagcloud` only turns it off as a widget option.

**Comment by JoryHogeveen** [comment]
Yep, I'll get to it

**Comment by JoryHogeveen** [comment]
Related https://core.trac.wordpress.org/ticket/36964

**Comment by JoryHogeveen** [comment]
@fireundubh This is moved to 2.7. If you can't wait for this major release you can filter your taxonomy options and labels as follows in your theme's functions.php:

```php
// Remove Tagcloud for all taxonomies
add_filter( 'pods_register_taxonomy', 'mytheme_disable_taxcloud' );
function mytheme_disable_taxcloud( $options ) {
    $options['labels']['popular_items'] = null;
    return $options;
}
```
Or
```php
// Remove Tagcloud for specific taxonomy
add_filter( 'pods_register_taxonomy', 'mytheme_disable_taxcloud', 10, 2 );
function mytheme_disable_taxcloud( $options, $taxonomy ) {
    if ( $taxonomy == 'my_taxonomy_name' ) {
        $options['labels']['popular_items'] = null;
    }
    return $options;
}
```

**Comment by fireundubh** [comment]
I don't think this filter is correct for WP 4.4+.

```php
add_filter( 'pods_register_taxonomy', 'mytheme_disable_taxcloud' );
```

While this filter does set the Popular Tags label to null, the Popular Tags cloud continues to render. I'm at a loss for why since `edit-tags.php` checks whether `!is_null( $tax->labels->popular_items )`.

The following filter, [register_taxonomy_args](http://adambrown.info/p/wp_hooks/hook/register_taxonomy_args?version=4.4&file=wp-includes/taxonomy.php), was introduced in 4.4. This piece of code will disable the Popular Tags cloud.

```php
add_filter( 'register_taxonomy_args', 'mytheme_disable_taxcloud' );
function mytheme_disable_taxcloud( $args, $taxonomy, $object_type ) {
	$args['labels']['popular_items'] = null;
	return $args;
}
```

I'm not sure whether there is an equivalent filter for Pods, specifically.

**Comment by JoryHogeveen** [comment]
@fireundubh 
Checked the code again and you are correct. 
Pods has a verification function placed after this filter that sets every empty value to a default so this will overwrite any `null` values. Sorry, didn't notice this...
The patch for 2.7 will work since this handles the `popular_item` value after the label verification.

Looks like the `register_taxonomy_args` or `taxonomy_labels_{$taxonomy}` filters are indeed your only options you have for now.

No clue as to why WP checks for a `null` value in the label instead of a setting like `show_tagcloud_in_edit` or something (that is the setting name I've chosen for the 2.7 patch which will force the `popular_items` label to be `null`).
