### ISSUE TITLE
Language folder is being removed in update

### ISSUE THREAD

**Issue by saulolago** [pods-framework/pods#3734]
In the last update, I have seen the folder languages being removed when upgrading Pods (automatic update for Wordpress). Before it was enough to just put back the language folder that the translation work (In my case Pt-Br), bad after the last update even replacing the Language folder the translation did not work. Could check please?
Thank you

**Comment by jimtrue** [comment]
Try two things, since you have your own language translations files:

1. Put your own translation files in the folder (wp-content/languages/plugins/)
2. Update your language for Pods on https://translate.wordpress.org/projects/wp-plugins/pods so moderators can review them for inclusion.

**Comment by JoryHogeveen** [comment]
Please also verify the file name. It should be `pods-pt_BR.mo` if I'm correct

**Comment by saulolago** [comment]
Yes, the files are with the correct names, but still does not work. In version 2.6.6 it works. In version 2.6.7 that is giving the problem.

http://www.awesomescreenshot.com/image/1503182/08352f3c63a0ec0ddcb796b10c7c6b1b

**Comment by JoryHogeveen** [comment]
The location in wp-content isn't correct.

For the .mo it should be:
`wp-content/languages/plugins/pods-pt_BR.mo`

**Comment by saulolago** [comment]
Sorted out.
Before the plugin has the language folder and removed the updates, so I kept that folder within the plugin. But the way it was mentioned solved the problem.
Thank you

**Comment by JoryHogeveen** [comment]
@saulolago 
Yep, since WP 4.6 the language structure is changed in leaning towards translate.wordpress.org.
Pods didn't distribute languages for a while but WP had always recognized the "old" way (and should still do though..).

Glad to hear this is fixed now. On the positive side, Pods updates won't remove your language files anymore ;)

Also, if you would like. You can put all your translations in here: https://translate.wordpress.org/locale/pt-br/default/wp-plugins/pods
This way it will be maintained withing WP core and it would help us in getting Pods translated for other users with pt_BR locale aswell!

I'll close this issue, thanks for reporting.
