### ISSUE TITLE
Depricated call (internal)

### ISSUE THREAD

**Issue by raptor235** [pods-framework/pods#3742]
Hey guys I started getting a warning from pods about a depricated use of a function... however the function call is coming from pods itself... 

PodsMeta.php
Line 2680
$meta_cache[ $meta_k ] = $pod->field( array( 'name' => $meta_k, 'single' => $single, 'get_meta' => true ) );

produces the warning

 Notice: Pods::field has been <strong>deprecated</strong> since Pods version 2.0! Use Use $params[ 'orderby' ] instead instead. in /code/dashboard.flowpress.dev/wp-content/plugins/pods/includes/general.php on line

**Comment by JoryHogeveen** [comment]
@raptor235 
Did some digging into the code.
I never got this message before so I would like to check something.

Is there a functioncall to `get_post_meta` or something similar in your theme that has a string type set for the `$single` parameter?

Something like:
```php
get_post_meta( $id, 'meta_key', 'true' );
```
Instead of:
```php
get_post_meta( $id, 'meta_key', true );
```

See https://github.com/pods-framework/pods/blob/2.x/classes/Pods.php#L709-L712

It appears to check if the `$single` variable is a string and if so, generates the notice.

@sc0ttkclark 
Maybe an idea to change a couple of lines in `PodsMeta.php` and cast the `$single` variable as a boolean.
Line 2680 and 2698

Change
```php
$meta_cache[ $meta_k ] = $pod->field( array( 'name' => $meta_k, 'single' => $single, 'get_meta' => true ) );
```

into:"
```php
$meta_cache[ $meta_k ] = $pod->field( array( 'name' => $meta_k, 'single' => (bool) $single, 'get_meta' => true ) );
```

**Comment by JoryHogeveen** [comment]
Or maybe set this in the beginning:

```php
$single = filter_var ($single, FILTER_VALIDATE_BOOLEAN );
```
