### ISSUE TITLE
Magic tags not rendering inside [once], [before] or [after]

### ISSUE THREAD

**Issue by regnskygge** [pods-framework/pods#3788]
For example...

```
[before]
<div class="{@checkoutable_syndication.slug}">
<h2>{@checkoutable_syndication}</h2>
[/before]
<div class="checkoutables-item item-type-{@checkoutable_syndication.slug}">
    <h3 class="item-name">{@item_name}</h3>
    <div class="item-description">{@item_description}</div>
</div>
[after]</div>[/after]
```

...renders...

```
<div class="{@checkoutable_syndication.slug}">

    <h2>{@checkoutable_syndication}</h2>

    <div class="checkoutables-item item-type-cables">
        <h3 class="item-name">30 Pin to VGA</h3>
        <div class="item-description">
            <p>30 Pin (Male) to VGA (Female)</p>
        </div>
    </div>

    ...

</div>
```

**Comment by regnskygge** [comment]
Actually, I believe there is a flaw in my logic here. Asking the template to instantiate a variable once (either before or after, also) when the variable is different for every item in the pod is not going to yield robust results.

**Comment by jimtrue** [comment]
It'd still be considered a bug as it's supposed to handle those within Template Tags, otherwise why have them?

What are you attempting to do with your output? There might be a workaround @regnskygge that would be a combination of template calling a shortcode calling another template.

**Comment by jimtrue** [comment]
[before] and [after] operate outside the Loop, that's why they don't return any values from the loop, or if they do, it's only the first records values or values that have nothing to do with the loop, like Special Magic Tags. This will not be corrected until we overhaul the Pods Templates at some point AFTER the current priorities.

[once] as far as I'm aware, has never worked. The primary use case for this one is to make the 'first' item in a series differently styled. Use CSS nth positioning for this.

**Comment by jimtrue** [comment]
Once documented here: https://docs.pods.io/displaying-pods/template-tags/once-template-tag/

Before and After Documented here: https://docs.pods.io/displaying-pods/template-tags/before-and-after/

Closing this as a non-issue as this is something we won't be able to handle until Templates are revisited.
