### ISSUE TITLE
Failing integration tests (_delete_all_data())

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3874]

**Comment by jamesgol** [comment]
Issue was introduced with WordPress core commit here https://core.trac.wordpress.org/changeset/38398
r38398 | wonderboymusic | 2016-08-27 01:35:16 -0700 (Sat, 27 Aug 2016) | 9 lines

> Unit Tests: 
> 
> * Automatically delete objects that we were created during `wpSetUpBeforeClass` - posts, comments, terms (except 1), and user (except 1)
> * The amount of leftover data between tests was breathtaking - use the new function: `_delete_all_data()`
> * Commit database transactions for all `TestCase`s, not just those that implement `wpSetUpBeforeClass` and `wpTearDownAfterClass`
> * The tests run 10-20 seconds faster now
> 
> See #37699.
> 
> 

The following is now called after every unit test class that derives from the WP test suite:
```
function _delete_all_data() {
	global $wpdb;

	foreach ( array(
		$wpdb->posts,
		$wpdb->postmeta,
		$wpdb->comments,
		$wpdb->commentmeta,
		$wpdb->term_relationships,
		$wpdb->termmeta
	) as $table ) {
		$wpdb->query( "DELETE FROM {$table}" );
	}

	foreach ( array(
		$wpdb->terms,
		$wpdb->term_taxonomy
	) as $table ) {
		$wpdb->query( "DELETE FROM {$table} WHERE term_id != 1" );
	}

	$wpdb->query( "UPDATE {$wpdb->term_taxonomy} SET count = 0" );

	$wpdb->query( "DELETE FROM {$wpdb->users} WHERE ID != 1" );
	$wpdb->query( "DELETE FROM {$wpdb->usermeta} WHERE user_id != 1" );
}

```

The Pods tests build all it's data here https://github.com/pods-framework/pods/blob/2.x/tests/phpunit/includes/testcase.php#L873-L874

The data setup should probably be called only when necessary for each class.  I believe all of that data is really only used for the traversal tests, so it might be wise to move all of that stuff into a different class instead of Pods_UnitTestCase which is used for all of the other tests.

**Comment by pglewis** [comment]
Also from @jamesgol:

> ... in /tmp/wordpress-tests-lib/includes/functions:_delete_all_data() if you have it just return instead of running all the delete queries, all the tests pass fine

Finding a clean way to bypass calls to `_delete_all_data()` except when needed looks like the solution, assuming failures do still fail with this approach.

**Comment by jamesgol** [comment]
That was really just a test to demonstrate what the issue is.  I think the proper solution is that have the class that needs that data built actually handle it.

I am pretty certain that only the tests-traversal.php tests are using that data, though there might be functions in Pods_UnitTestCase that are used by others.

I might have a bit of time later to look into this further.

**Comment by pglewis** [comment]
Right, not a proper solution but pinpoints the problem.

**Comment by szepeviktor** [comment]
Is there a temporary workaround to allow PR-s to pass?

**Comment by pglewis** [comment]
If you're looking to test locally to verify against the test suite you could install WordPress 4.6 under /tmp, where the tests run.  Otherwise I wouldn't worry about it for the moment.  All TravisCI tests are failing everywhere with 4.7, so we need to track it down and patch as a priority.

**Comment by szepeviktor** [comment]
Could we change `WP_VERSION=latest` to `WP_VERSION=4.6.1` meanwhile?

**Comment by pglewis** [comment]
I don't think it's going to be a difficult fix at first blush, so just hang tight.

**Comment by jamesgol** [comment]
Was looking into splitting up the code a bit so only the class that needs the built up data has it, but ran into an issue.  Gotta run out for a while so I wanted to leave some notes here.

I tried creating a new testcase-traversal.php that has a new class Pods_UnitTestCase_Traversal and tests-traversal.php uses that one instead.

The problem is that with phpunit and the data-provider.  From phpunit docs:

> Note: All data providers are executed before both the call to the setUpBeforeClass static method and the first call to the setUp method. Because of that you can't access any variables you create there from within a data provider. This is required in order for PHPUnit to be able to compute the total number of tests.

The data-provider we are using is generating the data based on the self::$builds array, which is built by the _initialize_config() function which also adds the Pods and saves the IDs in that array.  If you try to move the _initialize_config() and _initialize_data() to another point the data either doesn't exist or gets wiped out. 

@pglewis suggestion of just overriding their cleanup might be the best short term action.
Adding the following to Pods_UnitTestCase does that
```
	public static function tearDownAfterClass() {
	}
```

I suspect a revamp of the way the data is built for the traversal tests is in order, where the big array of possibilities is built independently of creating the Pods.
