### ISSUE TITLE
Sorting of custom fields not saving in the admin UI

### ISSUE THREAD

**Issue by scottjeter** [pods-framework/pods#3971]
After updating to Pods 2.6.8, the sorting for custom fields is not saving. Actually, after the update, any custom ordering of fields was removed entirely, defaulting to alphabetical order. This prompted me to try and re-sort the fields again but the admin wouldn't save my changes. 

In the admin UI, I'm able to drag the fields into the desired order without any javascript errors. However, after saving my changes, the sort order always reverts to alphabetical. Everything else is working (adding / editing fields), I'm just not able to save the order of the fields.

Admin page with the issue:
/wp-admin/admin.php?page=pods&action=edit&id=4

This was not an issue in 2.6.7, so whatever change was made to the latest version seems to have caused this bug.

**Comment by jimtrue** [comment]
I am unable to verify/reproduce this, so we may need some additional details.

I have replicated an Autocomplete relationship field and have tested manual sorting. I'm using a 'menu_order' sort (tested with an `[each relationship_field][/each]` block. Testing both on 2.6.7, I am able to drag and drop the 'order' around, save them and the order sticks. Likewise with the output, it always outputs in 'menu_order' since I'm not forcing an alphabetical sort.

Can you give us additional details to your setup, screenshots, etc?

**Comment by pglewis** [comment]
I know this has specifically been tested and verified in 2.7, at least.
