### ISSUE TITLE
Single File Upload field, src not available inside if/else

### ISSUE THREAD

**Issue by zushiba** [pods-framework/pods#3972]
My template code
`<td class="tg-yw4l">[if office_hrs_classes]<a href="{@_src}">View</a>[/else]Not Uploaded[/if]</td>`

The logic works, and correctly detects whether or not a file has been uploaded, but the src is not passed to to the template when rendered producing `<a href="">View</a>`

Also tried `{@office_hrs_classes._src}` with the same results.

**Comment by jimtrue** [comment]
For single file upload/image fields, within an `[if upload_file][/if]` you do need to use the full name of the file `{@upload_file._src}`. You only leave off the field name for `[each field_name][/each]` loops, because they are essentially stepping _into_ that file or relationship or taxonomy.

This was an issue inside IF blocks for single-select, but is working now as of #4408 If you test Pods 2.7 RC1 you should see this working now.
