### ISSUE TITLE
Feature request - syntax highlight WordPress and theme shortcodes

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods#3994]
Pods Framework works beautiful with WordPress and theme shortcodes, that's fantastic.

The "Template editor" already highlights Pods "magic tags" and shortcodes. It would be very helpful if this feature could be extended to highlight other shortcodes as well. Shortcode syntax is just as vulnerable to typos like all other code, and a different color for a shortcode, its attributes, ending tags and so on would help a lot.

![pods-feaure-request-shortcode-syntax-highligtning](https://cloud.githubusercontent.com/assets/17141205/22921622/ba0765fe-f29a-11e6-934c-fff810ecf0c8.png)

**Comment by jimtrue** [comment]
This would require a CodeMirror configuration change. We've got no 'real' way of recognizing every single shortcode out there. The only reason it recognizes "our" shortcodes is because they're not really shortcodes. They're logic branches (like if/else/endif and the format for them is changing in a future implementation of Pods Templates.

You can add your own configuration modes for CodeMirror supporting other shortcodes for your theme as follows:
http://codemirror.net/doc/manual.html#modeapi

But that is somewhat outside the scope for Pods, because we can't possibly support all the possible shortcodes there are out there.

**Comment by oldrup** [comment]
Ah. Thank's for clarifying this and pointing me in the right direction. Makes perfectly sense.  My goal is more highlighting any shortcode (stuff in brackets with attributes), than specific avada shortcodes. Maybe its time to dust of those rusty regexp skills and fiddle with a CodeMirror addon ;)

Have you got a link to more info on the mentioned changes in logic branches? They are VERY useful as is, but I'm sure curious of improvements. 

Finally a big thank you to anyone creating Pods - the potential for solutions created with WordPress has just increased dramatically to me 👍

**Comment by jimtrue** [comment]
You'll want to follow #3191 for details on all the items we're looking to add for Pods Templates Conditionals

And thanks for that, we're always working to improve Pods and we're happy you've added us to your arsenal.
