### ISSUE TITLE
Feature: Suggest a friendlier UI design to normal user

### ISSUE THREAD

**Issue by xkungfu** [pods-framework/pods#4009]
At first, I have compared toolset and pods and I choosed toolset.now after I had a  test to use pods, I think pods very more stronger than toolset.
so I suggest,after installing pods ,auto list all post_types, taxonomies and customer fields created by wordpress and other plugin at adin panel.
it is important that let the most options be showed to people clearly and directly.this will guide new user to study to use pods quickly.
study to use after installing immediately,not after creating something.creating is very diffcult to a new user ,because he don't know what will happen after creating.

**Comment by jimtrue** [comment]
@xkungfu Are you thinking that in addition to having our Add New & Extend Existing Wizard at the top to have a list of the existing WP Objects:
- Posts
- Pages
- Users
- Media
- Menus
- Comments
And maybe a break line and existing plugin Post Types

And beside those, a button to 'Extend'?

Once they were extended, they're considered 'Pods', because Pods is managing the Content Type or at least the additional fields and any interface with Pods Templates or the Pods Shortcodes or Widgets.

We have another issue to overhaul or incorporate the taxonomy view into the 'Edit Pod' screen to the Pods they're associated with. This would be so that you'd be able to use the Default WP Taxonomy handling for the field or override it with our 'picklist' (Select, Radio, Checkbox) input style to allow the additional enforcement of 1 selection or multiple selections, etc (and control who can see them)

If we did something similar with the 'default 'post' fields' which are currently controlled under Advanced Options, Supports, this might be a more holistic view for understanding how existing WP post fields work. Maybe even override the handling of them, or move them into field groups when we incorporate that into Pods. #799
