### ISSUE TITLE
Clean up "list view" for relationships (select from existing, dashicons, etc)

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#4019]
PR: #4032 
Part of 2.7: #3364

#### General 
- [x] support translation - 3fa214f
- [ ] Maybe add an option in the field setting to set a icon overwrite (dashicon)?
- [x] Use dashicons
- [x] Set the icon to the object type (of possible from the registered object)
- [x] UI element to initiate a selection list
- [x] selection list that shows/hides appropriately

#### CSS Tweaks
- [x] List view vertical alignment
- [x] Icon styles

#### Up for discussion
- [ ] Put buttons `select from existing` and `add new` side-by-side
- [ ] Auto-update button `add new` to the add new label of that object type (if available)

**Comment by pglewis** [comment]
A rudimentary solution is in place: "Select from existing" toggles between list view and checkbox view (which allows selecting new records).  Would need some CSS love and possibly fixed sized containers so things don't move around so much, but it is usable now.

**Comment by jimtrue** [comment]
Comment on the Select from Existing, when you flip back and forth between the 'selected' view and the Select from Existing, it's a little jarring because the line heights/icon heights are not the same. I think it'd be smartest to make the icons all the same height/width ratio, line-heights consistent for the draggable icon, the icon for the post-type/featured image, and the 3 'action ones' to the right 'edit or delete'; I'd switch that from a 'link' icon to a 'view' icon if that's opening a link to the front-end version of the post. I was checking but there seems to be some inconsistency, with some 25 x 32 blocks and a 40 x 32 block. 
![screenshot 2017-03-15 19 17 43](https://cloud.githubusercontent.com/assets/3052875/23974891/1d991c4a-09b4-11e7-9f89-25454980243e.png)

**Comment by pglewis** [comment]
There's also a brainstorming idea to add a new option for list view that allows you to choose the "select from existing" UI.
