### ISSUE TITLE
Db table doesn't exist on post type & taxonomy relationship (related to #2088)

### ISSUE THREAD

**Issue by zmni** [pods-framework/pods#4130]
Related to #2088.

WP version `4.7.4`
Pods version `2.6.8`
Field Type: `Relationship (Custom Taxonomy/Post Type)`

Screenshot from `http://lombokabang.dev/app/wp-admin/post-new.php?post_type=workshop&pods_debug_sql=1` : 
![pods1](https://cloud.githubusercontent.com/assets/841523/25413833/735d958e-2a57-11e7-9e84-b4927873ebe3.jpg)

My `$table_prefix = 'lombokabang__';` with double underscore, but Pods query them with single underscore.

**Comment by antoinepat** [comment]
Same issue with my db prefix having double underscores

**Comment by quasel** [comment]
Sorry for the late reply, is this still an issue? #2088 another user with the sam issue - @sc0ttkclark does that sound familiar?

**Comment by juniperpaul** [comment]
Yes, this is still an issue! For over a decade I have routinely used a double underscore in my table prefixes, e.g. `project_this__wp_posts` because, when more than one project is in the same database, phpMyAdmin conveniently groups them:
```
+ project_this (13)
+ project_that (22)
```
etc.

Quickly perusing the Pods code, I see at least one possible cause of this problem in `function pods_clean_name()` in `pods.2.7.11/pods/includes/data.php` where multiple underscores are explicitly preg_replaced with single underscores:
```
1328    $str = preg_replace( '/(_){2,}/', '_', $str );
```

I suspect the rationale for that line is that each whitespace has just been replaced with an underscore:
```
1326    $str = preg_replace( '/(\s)/', '_', $str );
```
and then line 1328 is supposed to replace multiple whitespace characters into single underscores but inadvertently mangles names that originally intentionally contain multiple underscores.

I suggest that better logic would be to replace multiple whitespace characters with single underscores in line 1326:
```
$str = preg_replace( '/(\s)+/', '_', $str );
```
and remove 1328 entirely.

I haven't examined the Pods code to see if this logical flaw occurs in other locations as well.

Nice plugin, though~
Paul

**Comment by sc0ttkclark** [comment]
This is a good point, we should definitely add support for consecutive underscores.
