### ISSUE TITLE
Pod post not publishing content

### ISSUE THREAD

**Issue by sassteve** [pods-framework/pods#4182]
After following the instructions word for word on the pods OSTraining videos, the published pod post only shows the title of the post and not the content.

The pod Books has three fields and is connected to the Books Template, which is done so in the Auto Template Options in the _Single item view template_ field. What is the pod missing in order to function correctly?

Wordpress Version 4.7.4
Pods - Custom Content Types and Fields Version 2.6.8

**Comment by jimtrue** [comment]
This isn't a bug, this is actually a support question and you should send this through our typical support channels: http://pods.io/forums/ or on our Slack Chat at http://pods.io/chat/

It will also help if you provide a screen shot of your Pods Template and your Auto Templates. Also our standard troubleshooting especially since Auto Templates requires the_content filter in the theme to function (which is what outputs the information from the 'Editor' box in the post), I always recommend switching to a default WP Twenty-"something" theme and making sure no other plugins are conflicting.

**Comment by sassteve** [comment]
Thank you jimtrue for the recommendations! I hope to be able to figure out the issues.
