### ISSUE TITLE
Implement Tiled View for images in DFV

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#4258]
PR: #4510 

![pasted image at 2017_05_24 20_10](https://cloud.githubusercontent.com/assets/9464217/26418638/4168547a-40bd-11e7-9e90-0f992f52644e.png)

Has even a help Text ;)

**Comment by jimtrue** [comment]
yeah the file list is supposed to flip from Rows, to Tiles and you are correct, the option above doesn't do anything.

**Comment by quasel** [comment]
add to it remove option for single select!

**Comment by JoryHogeveen** [comment]
Is used to actually switch the field type layout. Rows should display a similar layout are DFV relationships while Tiles should display this: #3589

Just checked as well and it seems that the new DFV structure isn't changing anything.
See the changes from this line/diff: https://github.com/pods-framework/pods/pull/3589/files#diff-c8eb20cd5017aed80c9902cf5c2d3795R22

@pglewis Any ideas?

**Comment by pglewis** [comment]
`ui/fields/media.php` is dead code in 2.7, replaced entirely by the DFV implementation.  This is probably something I completely missed as a view for DFV.

**Comment by JoryHogeveen** [comment]
@pglewis 
Just some info for when you are merging to DFV:

- Sortable can go both horizontal and vertical:
https://github.com/pods-framework/pods/pull/3589/files#diff-c8eb20cd5017aed80c9902cf5c2d3795R29

- I changed removal of items to a fade out instead of slide up. Looks better for tiles mode.
https://github.com/pods-framework/pods/pull/3589/files#diff-c8eb20cd5017aed80c9902cf5c2d3795R183

- The CSS is simply checking the container class. (Might be that we need to change this class for DFV??)
https://github.com/pods-framework/pods/pull/3589/files#diff-c8eb20cd5017aed80c9902cf5c2d3795R25
CSS: https://github.com/pods-framework/pods/pull/3589/files#diff-c4c7dc31e35c8e5875db5a105a4c7338R143

**Comment by pglewis** [comment]
Looks like the CSS classes got updated along the way but some of it may need some tweaking.  I'm getting an unnecessary scrollbar on Ubuntu/Chromium.

**Comment by pglewis** [comment]
Also, looks like the sort axis code made it into DFV but the fade out might be a little trickier.  The way I've implemented it, I believe we just destroy the whole view and redraw a new one whenever the underlying model changes (like when removing an image).

**Comment by JoryHogeveen** [comment]
>  I'm getting an unnecessary scrollbar on Ubuntu/Chromium.
Vertical or horizontal?

> but the fade out might be a little trickier.
It removes instantly now, that is fine with me :)

**Comment by pglewis** [comment]
Scrollbar problem is gone.  Looks good at a glance here.
