### ISSUE TITLE
Upgrade to 2.6.9 Broke IF functionality in Templates, outputting shortcodes

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#4308]
This is from this forum post: http://pods.io/forums/topic/update-to-2-6-9-if-clauses-in-templates-broken/

I just updated to pods_2.6.9, but had to roll back after realizing it did no longer evaluate [IF] clauses in pods templates. Here’s one line that used to work under 2.6.8, but doesn’t under 2.6.9:
```
<img class="logo" src="[if video_thumbnail]{@video_thumbnail}[else]{@post_thumbnail_url.thumbnail}[/if]">
```
`video_thumbnail` is a custom field within the pod.

**Comment by jimtrue** [comment]
After communicating, provided me with the inspector values of what was outputting:

Thanks for looking into this, much appreciated! I’ve got 2 examples for you with different field types. Let me know if you need anything else! I might stick with 2.6.8 for now: I’ve got IF clauses dotted all over my website, replacing them would be pretty tedious.

**field type:**
`video_thumbnail` is of type `File/Image/Video`.

**template:**
```
<img class="logo" src="[if video_thumbnail]{@video_thumbnail}[else]{@post_thumbnail_url.thumbnail}[/if]">
```

**2.6.8 output:**
`<img class="logo" src="http://path/to/thumbnail.jpg">`

**2.6.9 output:**
```
<img class="logo" src="[pod_if_field id=" 2217"="" pod="video" field="video_thumbnail" index="{_index}" seq="0" ]e0b2awrlb190ahvtym5hawx9w2vsc2vde0bwb3n0x3rodw1ibmfpbf91cmwudgh1bwjuywlsfq="=[/pod_if_field]&quot;">
```

**field type:**
`race_date_confirmed` is of type `Yes / No`.

**template:**
```
<p style="display:[if race_date_confirmed]none[else]inline[/if]"> (unconfirmed)</p>
```
**2.6.8 output:**
`<p style="display:inline"> (unconfirmed)</p>`

**2.6.9 output:**
```
<p style="display:[pod_if_field id=" 643"="" pod="race" field="race_date_confirmed" index="{_index}" seq="0" ]bm9uzvtlbhnlxwlubgluzq="=[/pod_if_field]&quot;"> (unconfirmed)</p>
```

Asking client to submit full text of template to this issue.

**Comment by mstummer** [comment]
Hey Jim! Sorry, slow reply... I've been away for a couple days. On the original pods forum post you asked me to 'upload the template'... not exactly sure what you need there. If you still need anything from me just shoot me a line...

Max

**Comment by jimtrue** [comment]
@mstummer No worries and apologize for taking so long to reply on yours as well. We have a fix for you if you're willing to test it:

1) Copy your existing /pods/ plugin from /wp-content/plugins/pods/ into a /wp-content/plugins/backups/ directory (you'll probably have to make this one) (you can do this on your CPanel on your webhost or through FTP/SFTP.
2) Download the following version of Pods: https://github.com/pods-framework/pods/issues/4324
3) Install through the Plugin, Add New, Upload screen, or unzip the file above into your /wp-content/plugins/ directory. WordPress will recognize it as 'Pods'

Test! If it works, let us know back here. If it doesn't, let us know how it's still broken.

Thanks!

**Comment by regnskygge** [comment]
2.6.10-a-1 seems to have addressed https://github.com/pods-framework/pods/issues/4307. Yay!

**Comment by mstummer** [comment]
I had replied to the #4324 thread, but here my reply for the record:

Hey Jim!

Thanks for the update and instructions! Quick story: it seems to have fixed the issue!

First I tried to reproduce the issue on my dev server by updating 2.6.8>2.6.9 . Funny enough I couldn't reproduce the issue. I had done the same when we launched the ticket, and back then the issue was visible as described. I had also deactivated all other plugins one by one on that dev server to see if there was any interference, but the issue persisted.
Now I updated to 2.6.9, and the issue did not occur. I mess around with that dev server a lot, so lots of things have changed since. So there must be something else involved, but I couldn't tell you what it is.
So I went for my live website (yikes) and updated with 2.6.9, which displayed the issue immediately. Removing that plugin and installing #4324 solved the issue.

Thanks for the awesome support and all the time you spend on this!
Let me know if I can do anything else!

Max
