### ISSUE TITLE
Templates inside HTML broken after Updating Pods

### ISSUE THREAD

**Issue by imarcos22** [pods-framework/pods#4324]
```
<div class="free-it">
    <div class="free-th">
        <a target="blank" href="[if url]
{@url}
[else]
{@permalink}
[/if]"><img src="{@image._src}"></a>
    </div>
    <div class="free-ct"><a target="blank" href="[if url]
{@url}
[else]
{@permalink}
[/if]"><span>{@post_title}</span></a></div>
</div>
```

**Becomes this on the front end:**

```
<a target="blank" href="[pod_if_field id=" 56428"=""  field="url" index="{_index}" seq="2" ]dqp7qhvybh0ncltlbhnlxq0ke0bwzxjtywxpbmt9dqo="[/pod_if_field]
```

**Comment by jimtrue** [comment]
Additional notes from Slack Chat: This was used in a widget @imarcos22 if you have time, could you provide your settings for the widget? ie was it a text widget calling a shortcode or were you using a Single Item Pods Widget?

**Comment by jimtrue** [comment]
Adding to #4309 Epic

**Comment by jimtrue** [comment]
@imarcos22 is using a Single Item Pods Widget. I'm guessing with the checkmark for current post.

**Comment by imarcos22** [comment]
I'm using the Pods - List Items

**Comment by jimtrue** [comment]
Oh you just posted you were using Single Items Widget. So this is a List Items Widget. Can you screenshot and upload your configuration for that widget?

**Comment by imarcos22** [comment]
![image](https://user-images.githubusercontent.com/8343688/27500159-0c6eadb6-581c-11e7-8309-e9990957c3af.png)

**Comment by jimtrue** [comment]
Got it, perfect and thanks!

**Comment by pglewis** [comment]
This was introduced in the commit @sc0ttkclark hunted down, https://github.com/pods-framework/pods/commit/e9562e30987d8b2a57883ddc81df7482362bd546 from #3997.  That PR addresses no fewer than seven other issues, however, so I'm not keen to simply revert it.

**Comment by pglewis** [comment]
As a possible workaround: try changing to single quotes around the Pods' `if` template for the href: 

```<div class="free-it">
	<div class="free-th">
		<a target="blank" href='
                    [if url]
				{@url}
                    [else]
				{@permalink}
                    [/if]
		'><img src="{@image._src}"></a>
    </div>
    <div class="free-ct">
		<a target="blank" href='
			[if url]
				{@url}
		        [else]
				{@permalink}
			[/if]
		'><span>{@post_title}</span></a>
	</div>
</div>```

**Comment by pglewis** [comment]
PR: #4335

**Comment by jimtrue** [comment]
@imarcos22 Can you test to with this version of Pods and see if it fixes your issues?
https://github.com/pods-framework/pods/archive/feature/4324-shortcodes-in-html.zip

Just copy your wp-content/plugins/pods/ into a backup directory and drop install the version of pods in the zip from the link above. This includes the fix that should rectify your issue.

Thanks!

**Comment by regnskygge** [comment]
2.6.10-a-1 seems to have addressed this issue. Yay!

**Comment by mstummer** [comment]
Hey Jim!

Thanks for the update and instructions! Quick story: it seems to have fixed the issue!

First I tried to reproduce the issue on my dev server by updating 2.6.8>2.6.9 . Funny enough I couldn't reproduce the issue. I had done the same when we launched the ticket, and back then the issue was visible as described. I had also deactivated all other plugins one by one on that dev server to see if there was any interference, but the issue persisted.
Now I updated to 2.6.9, and the issue did not occur. I mess around with that dev server a lot, so lots of things have changed since. So there must be something else involved, but I couldn't tell you what it is.
So I went for my live website (yikes) and updated with 2.6.9, which displayed the issue immediately. Removing that plugin and installing #4324 solved the issue.

Thanks for the awesome support and all the time you spend on this!
Let me know if I can do anything else!

Max

**Comment by pglewis** [comment]
For the sake of history I should clarify: this was an edge case specifically with Pods shortcodes inside HTML _attributes_, not necessarily any shortcode embedded in HTML.  

The problem is Pods `if` templates will expand internally and the resulting shortcode will contain quotes.  If those quotes are embedded inside other quotes in an HTML attribute it breaks some kses parsing that WordPress attempts whenever you call `do_shortcode`.
