### ISSUE TITLE
Allow access to disabled post features via REST API

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4339]
I have a scenario where a specific post has it's post title or author fields disabled in the Pods UI. 

<img width="737" alt="screen shot 2017-07-07 at 19 21 32" src="https://user-images.githubusercontent.com/12051736/27971173-8d5702b0-6349-11e7-8856-76cc236ca052.png">

However, for various reason we still need to be able to access these disabled fields using the WP REST API. One specific use case is where the `post_title` field is auto-set by the system (for relationship select field purposes) and we need to use functional tests to verify that a post is assigned the correct title. If the `post_title` field is disabled in Pods, it's not available via the API either.

Ideally, we should be able to select whether each of these "Supports" options is enabled/disabled for REST/UI or both.

If the above isn't possible, is there a hook or function where it would be possible to override these "supports" for REST/UI on a per-post basis?

**Comment by sc0ttkclark** [comment]
Not possible with supports itself, but maybe what you might be wanting is not to remove an attribute entirely (remove from supports) but to hide the UI element. So perhaps we could come up with a new list that would supplement supports by removing certain hooks in the UI to disable the fields from showing.

**Comment by jimtrue** [comment]
Wouldn't it be just as easy to make those fields only visible by capability? Or would that mean the REST API wouldn't have access to them unless the account using the REST API had those capabilities?

**Comment by jimtrue** [comment]
Also, I forgot since those are WP Object post type fields, we're not controlling them any other way than through the WP Core post_register methods. We don't have our Visibility controls for those fields. As far as I know, WP doesn't do anything special for those fields _either_ if you turn off 'supports' for them. 

Have you reached out to the REST API team over on WordPress slack to see what their suggested solutions are for this particular issue? You can't be the only one who has run into this. This isn't specifically Pods, but more REST API handling for parts of the default wp_post through `register_post`

**Comment by lougreenwood** [comment]
@jimtrue & @sc0ttkclark - thanks guys, some good advice here. I've created a ticket for WP REST (https://core.trac.wordpress.org/ticket/41273#ticket).

I'm thinking that I might be able to work around this by overriding `add_post_type_support()` when a REST request is detected and a specified user ID or role is detected. Although I need to do some research before I know whether this is possible.

Feel free to close out this ticket - thanks again 👍

**Comment by lougreenwood** [comment]
closing as this is a WP issue
