### ISSUE TITLE
Repeater (Loop) field

### ISSUE THREAD

**Issue by StaggerLeee** [pods-framework/pods#4340]
Shall we wait 5 more years to see it ?
I know you will be pissed off now. :)

You have to admit a veeeeeeeeeeeeery long time passed. Dont know even how to say it because it is free work, free (others) time. But have to say it. Even bbPress and buddyPress communities look like vibrant beehive, compared to yours.

I believe you have some issues and problems with planning, not the code and coding talent.

Will close it, not an issue, just something I had to say.

**Comment by jimtrue** [comment]
If you have something to say, there are better places to do it and better ways to say it, including reaching out to us directly. 

What you have been doing instead is the classification of an "internet troll" and you have been blocked from our project. 

Open Source projects are about community; they are about helping to make the project better through code contributions, finding bugs or offers of help in whatever manner that can be. Your contributions have been targeted only to deride, debase or encourage others to defund this project. Your contributions are not welcome here.

**Comment by jimtrue** [comment]
If you had been paying attention to the project, the 2.7 Beta has been out for more than a month and is due to be released this month. It is the result of extremely hard work by our incredibly talented developers and is the proper way to handle 'loop fields':
https://www.youtube.com/watch?v=1h_5tQ6LmoY
https://pods.io/pods-beta/

**Comment by sc0ttkclark** [comment]
Pods 2.0 was a big release for us. We tackled a major rewrite and major admin UI revamp. We did a lot of stuff under the hood, but ultimately fell short of all of our goals. We built new forms and form fields that let us do much more for Pods in 2.x itself. However, much of what we built did not directly translate into where JS was going in the future years and it has hindered our ability to build Loop Fields / Repeatable Fields.

As a result, in Pods 2.7 we started work on rewriting all of our fields over to our new structure we're calling Dynamic Field Views (DFV for short). These will allow us to spin up new fields in a form with JS models and data objects, without worrying about hacking the DOM or losing track of states. This work was done for Relationship fields and File upload fields. We'll continue this work in Pods 2.8 for other field types, which will enable us to run a very speedy Pods 2.9 release to let Repeatable fields out to shine for the world to enjoy.

Pods 3.0 is our main focus for Loop fields and we're hoping to provide the same UI that Loop fields would provide, in a way that can be leveraged as relationships so that data isn't merely stored in serialized/json objects in the database. There's also the trickiness of table vs meta storage because we support so many different types of objects in Pods.

bbPress and BuddyPress both enjoy a large amount of time and $ investment as major flagship products which are essentially sisters to the WordPress project itself. Pods doesn't get that much sponsorship. They are also entirely different projects, focusing on features for websites -- not features for developers / website builders like Pods is. So to compare those against Pods is pretty difficult since there are so many levels of differences.

We have a great community growing on our Slack and contributors on our GitHub have continued to bring forth excellent contributions/PRs.

We look forward to building some really great features in the coming major releases of Pods, we hope you'll return to give us another chance when that happens. Otherwise, if Pods isn't a great fit for you at that point, I'm sure that there's a better solution for your needs and that's awesome. We're 100% behind you in ensuring your projects excel with the tools you choose.

Creating these types of issues or leaving comments in the way you did isn't really helpful for us, since it clogs up our issues list with things that aren't bugs or features. In the past, we've seen the same sort of activity from you. I totally understand you're frustrated and want us to succeed, but there are better ways to contribute and support us.

Consider this a warning, any future abuse of our GitHub issues will be met with a temporary ban or permanent ban from our GitHub. This isn't because we don't like you, we in fact love your passion! We just want to ensure that our GitHub remains a vibrant place for our contributors to do their work without worrying about distractions that aren't helpful like these.
