### ISSUE TITLE
User Meta within pod templates Not Showing. 

### ISSUE THREAD

**Issue by ChrisO2134** [pods-framework/pods#4413]
Here are 2 examples of me trying to use user meta data within my template. I've added the special magic tag code to wp_config file to be able to show user data within a template, but getting nothing. 

shortcode example ...

[pods name="deals" limit="3" where="category.slug='live' AND post_author='{@user.ID}' " orderby="post_date DESC" template="deal_simple_mypage"] 

Post content example ...

<h2>Welcome {@user.user_name} to the page you made!</h2>

**Comment by jimtrue** [comment]
@ChrisO2134 The WP_Config code is designed to allow you to use {@user._any_} in shortcode's where statements. It relates to the currently logged in user.

Using {@user.user_name} isn't going to return anything in a Pods Template because special magic tags don't do that. Your template should include `{@user_name}` in order to properly reference that user in the 'loop', if you're referencing a field in `user`. Since your shortcode is actually against `deals`, you'd need to have a relationship field into `user` to display `{@related_user.user_name}` or call against one of the get_the_author functions, ie `{@post_author,get_the_author}`. There does not currently exist automatic traversal between the post_author and related user_meta/user content unless you _explicitly_ define a relationship field back. See #4119 

Nothing looks wrong in your shortcode above; post_author will return the numeric ID so it should properly match to the logged in user.

**Comment by quasel** [comment]
See #4484

**Comment by jimtrue** [comment]
@quasel this is not related {@user._any_} is a Special Magic Tag and has no relationship to a Related User object.

This needs to stay open and assigned to me, because this is a Docs Improvement.

**Comment by jimtrue** [comment]
Updated: https://docs.pods.io/displaying-pods/magic-tags/special-magic-tags/#Usage_and_Caveats
