### ISSUE TITLE
2.7 RC1: Relationship field doesn't appear at attachment page (upload.php)

### ISSUE THREAD

**Issue by Enuriru** [pods-framework/pods#4462]
<img width="675" alt="untitled-1" src="https://user-images.githubusercontent.com/19951129/30262476-454a61f2-96fb-11e7-8c63-0b4ba0764fd9.png">

**Comment by pglewis** [comment]
Anything in the Javascript console?  

I'll take a look, this is an edge case that hasn't been tested as widely.

**Comment by pglewis** [comment]
We just need to make sure our DFV gets enqueued there.  No errors, but the raw JSON describing the field is left sitting there, unprocessed.

**Comment by Enuriru** [comment]
Yep, no errors in the console. Also WYSIWYG field is buggy too:

<img width="529" alt="2017-10-07 22 20 30" src="https://user-images.githubusercontent.com/19951129/31309273-cfa573d4-abad-11e7-806c-4797c6d7748c.png">

**Comment by pglewis** [comment]
Interestingly, when the media library page in the admin loads, it calls through to get the meta fields for every item on the main page load but it doesn't render the fields until an item is clicked and it opens in the modal.  We no longer render the fields in raw markup, we drop a data script with JSON that describes the field to be built.  

Probably just a matter of making sure we do a sweep for any of our data scripts in places like this, hopefully it doesn't present a challenge finding a place we can initiate that.

**Comment by pglewis** [comment]
Also note this only happens in "grid mode", list mode doesn't open items in the modal.

**Comment by pglewis** [comment]
We've done a lot of homework on this and it boils down to some limitations with how the media library handles meta fields for edits in the grid mode modal.  

The media library assumes the meta fields will be simple, static HTML form fields and does not seem to have any provision for dynamic fields that may have multiple components (like select2 or the new List View for 2.7).  

There is a workaround by editing the media item in "list mode" rather than "grid mode".  That is not a proper solution, we're never happy when anything doesn't integrate properly no matter how small or if there is a workaround.  But a proper solution to this that doesn't introduce more issues than it fixes seems complex enough that I'd like to propose pushing it to 2.7.1 rather than hold up 2.7 release.  

@sc0ttkclark, @Enuriru let me know what you think

**Comment by sc0ttkclark** [comment]
+1 on giving it more time

**Comment by Enuriru** [comment]
I think it's enough to make simple <select> work (like in pods 2.6) if it's possible.
And when there is something more complicated like WYSIWYG/select2/list view just display an "Edit..." link leading to attachment edit page where all these files works ok.

**Comment by pglewis** [comment]
That needs a little further thought but would be my current top choice of interim solutions if it's doable without pushing 2.7 back 2-400 weeks.

**Comment by pglewis** [comment]
Ultimately I think the right thing to do is contribute something to WordPress core so it can painlessly support dynamic fields in this context.

**Comment by pglewis** [comment]
Not quite ready to move the milestone, there is still some action for me to take before release so I want it to show up in my filter for 2.7 issues.

**Comment by pglewis** [comment]
And the breadcrumb trail to date, these are the two biggest hurdles I've found thus far:

1. Every time a modal edit window renders from the media library in grid mode, it uses the HTML that was stored in the model from the initial AJAX request at page load:

https://github.com/WordPress/WordPress/blob/d21f679/wp-includes/js/media-views.js#L8330

That is a snapshot it retrieved at page load going straight to the page via `html()` and does not take into account dynamic controls that may add, modify, and delete things in their actual DOM representation.  DFV relationships get initialized with data for the currently selected items at page load and that data as well as the actual markup to represent it must be able to change and not re-initialize from old state.  

There may be kosher ways to hook in and modify the model data initially (I haven't gotten that deep) but it would still need to update `compat.item` between opening and closing the modal window each time.  

2. They dynamically save on any change events to any input, select, or textarea: 

https://github.com/WordPress/WordPress/blob/d21f679/wp-includes/js/media-views.js#L8300-L8302

This works for the case of a single static form element but can't reliably support a rich workflow UI that might incorporate multiple input and select elements in its implementation.  

I'm pretty sure we could handle both those situations with an extended `AttachmentCompat` object tailored to the needs of the component but that just moves the goal posts to "how do we inject our custom object".

**Comment by pglewis** [comment]
The saving concern (2) might mostly evaporate with some luck.  The media's underlying model should be updated on save as long as our handler for `attachment_fields_to_save` does everything right.  It still generates a lot of mistaken ajax traffic in a select2 environment (autocomplete, list view) due to the dummy input field it uses and doesn't quite work right.  But enqueueing the scripts we need, making some style tweaks, and manually initializing the DFV field from the console it's sooooo close.  

![modal-edit](https://user-images.githubusercontent.com/1973916/32302190-d3a0d6b6-bf37-11e7-93ad-1c727271c499.png)

**Comment by pglewis** [comment]
> I'm pretty sure we could handle both those situations with an extended AttachmentCompat object tailored to the needs of the component but that just moves the goal posts to "how do we inject our custom object".

This is looking like the best option if I can get it to pass the "what if every plugin I have does this" smell.  It has to be done in a way that can co-exist with other plugins that may need to do a similar thing.

**Comment by pglewis** [comment]
#4785 fixes basic fields and #4798 has been created for the remaining issues.  Closing this one out.

**Comment by pglewis** [comment]
This will also need some CSS tweaking for pick fields in media items in grid mode.
