### ISSUE TITLE
DFV CSS settings pages

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#4518]
The UI for setting pages is not 100% for DFV fields due to styles added by `_admin.scss`.
Some of these styles are needed though. Any ideas on CSS structure are welcome.

![image](https://user-images.githubusercontent.com/826148/31624332-a7c8f1aa-b2a2-11e7-8705-f9055d67c8cc.png)

**Comment by pglewis** [comment]
Working backwards from what I'd like to ultimately see, these are the built style files I think we need: 

- "Main" pods.css file, limited to admin pages, contains most of what we need
- wizard styles, extracted for some size savings in the main file because they're only needed in specific places
- styles needed for the front end only (eventually probably named 'pods-front.css').  We want to keep the stylesheet overhead on front-end pages to a minimum.  

The intention thus far has been for 'pods-form.css' to transition into 'pods-front.css' but I don't think we're quite there yet.  As the name suggests, it was originally styles for where PodsForm is used and those are more scattered than the breakdown we're after.  

I'm open to discussion on that breakdown, that's just what I've had in mind thus far.

**Comment by nicdford** [comment]
I think @pglewis is on the right track. I think the biggest issue we had before was just some overlapping of styles and it could probably get into ship-shape with a good review/rewrite. I'm happy to take on _admin.scss since that's the main culprit at the moment.

**Comment by pglewis** [comment]
Proposed patch in #4526
