### ISSUE TITLE
Custom taxonomy related to ACT doesn't display translated with WPML

### ISSUE THREAD

**Issue by manuel-84** [pods-framework/pods#4556]
Hello, I have setup and advanced content type with table storage and one of its fields is a relationship to a custom taxonomy (table storage again). I have WPML and I have translated this custom taxonomy but when I show data from the related field it always display using the main language.
If in WPML i turn on the option "Rectified IDs for multilingual functionality" the field doesn't get displayed at all.

**Comment by jimtrue** [comment]
Advanced Content Types would not be able to integrate with WPML's or Polylang's default configuration (without a custom add-on) because they exist outside of WordPress's default Custom Post Type/Taxonomy infrastructure. @JoryHogeveen can weigh in on this one, but I honestly don't think this is something we could get integrated without someone taking this on as a special project, since external tables by default are not translated by WPML or any of the translation engines.

If you switch to Custom Post Types and Custom Taxonomy, you should be properly supported by WPML and Polylang.

**Comment by JoryHogeveen** [comment]
This would definitely be a separate compatibility tool since WPML and Polylang depend on the use of WP core objects (`WP_Post`, `WP_Term` etc).
It _might_ be possible to make the `PodsObject` compatible once it's here in 2.8 but I don't think this would be in the scope of Pods core.

**Comment by quasel** [comment]
Hi, we didn't hear back from you - so I'm closing the issue! And that's clearly a very special use case due to nature of ACT and how WP works ^^
