### ISSUE TITLE
Problems with the "Additional user features" and "Show in Admin menu New Bar Menu".

### ISSUE THREAD

**Issue by KaueAlves** [pods-framework/pods#4557]
When you check the two options together, they work perfectly, however, when you check "Additional user capabilities" and do not check "Show in administration bar" New "Menu," the "edit post" option is not enabled.

**Comment by jimtrue** [comment]
This was a cross-post from WordPress.org forums:
https://wordpress.org/support/topic/how-to-enable-edit-post-in-the-wp-admin-bar-in-my-custom-post/ Closed that issue and will continute research in GitHub.

@KaueAlves We need some additional information from you:

- Checking **Additional User Capabilities**, which is checked by default, allows the edit_published_ capability. If you uncheck that, once the post is published, you won't have this capability any longer. You can verify this by looking at the post list and if it switches from Edit | View | Delete to just 'View' then it's not showing Edit Post because your role no longer has the rights to 'edit_published' or 'delete_published' etc. granted by Additional User Capabilities.

- The **'Show in Admin Bar "New" Menu** is what actually allows the 'Edit Post' option to show at the top of the screen, basically it is what allows for Admin Bar management.

If you verify the above and still feel there is an issue, please let us know.

**Comment by KaueAlves** [comment]
Many thanks, I was trying to keep the ** Edit-Post ** without adding post-type to the **+New **.
I'm working with 85 custom posts, so the "+ new" is extremely extensive.

Is there any option to remove them from the "+New"?

**Comment by quasel** [comment]
Sorry for the late reply, feel free to comment if you still have questions!
