### ISSUE TITLE
Taggable not allowing to add new tags

### ISSUE THREAD

**Issue by CPapadim** [pods-framework/pods#4565]
Using latest 2.7 beta

I have a custom content type made in Pods, with a relationship field pointing to a custom taxonomy also made in pods.  I'm trying to use taggable option under the field options, so that new tags can be added, but it doesn't seem to do anything.  

I tried both with single and multi select as well.

**Comment by jimtrue** [comment]
Can you confirm you could do this in 2.6.11?

**Comment by CPapadim** [comment]
I can't, I don't have an install of 2.6.11, I'm a new user, and since I needed the Flexible Relationships functionality I went right ahead with the 2.7 beta

**Comment by jimtrue** [comment]
Typically with Taxonomy, you associate the taxonomy to the post type (under Advanced Options for the Post Type, down at the bottom) and you use the 'taggable' option that is built into WordPress Taxonomy fields (you add new taxonomies directly in WordPress). We don't recommend using relationship fields to taxonomy because that's double-work and usually creates odd issues in the long run.

**Comment by jimtrue** [comment]
Flexible Relationships don't work with Custom Taxonomy at all, which is an issue with Taxonomy handling from WordPress. We couldn't get them incorporated with 2.7 so we had to draw a hard-line in that particular feature that is something we couldn't support.

**Comment by CPapadim** [comment]
Right, I'm not using the taxonomy as a flexible relationship, just as a regular field.  I needed Flexible Relationships for something else entirely, which si why I got 2.7 version.  I can switch over to using Wordpress tagging as you suggest, but it's just not as nice for workflow because it appears in its own separate column rather than as part of the fields in the main body.  

I guess to me it's sort of odd that you're saying not to use the Pods Taxonomy field - if it's not meant to be used, why is it an option? 

But with that said, yeah, I can definitely work around this issue :)  I just thought I'd report it in case it was user error, or you guys wanted to fix it in a future version.

**Comment by jimtrue** [comment]
No, I'm saying don't use a 'relationship to a taxonomy' when your intent is to use a Taxonomy field.

It's a backwards compatibility request for folks who truly are using Taxonomy as a relationship just to have a tightly controlled list of options that the end-user can't edit and also for Advanced Content Types which didn't have any support for Taxonomy.

However, if your goal is to use Taxonomy as it's intended to be used with WordPress, you need to use Associated Taxonomy and not a relationship field to Taxonomy. Especially, if you want other plugins to filter and group and do everything Taxonomies are supposed to do.

We have a plan to overhaul the handling and display of taxonomy (because _everyone_ wants Taxonomy to display and be handled like our relationship fields), but doing that and still BE WordPress taxonomies is a patch release all on its own. It's slated for a future release, regardless.

**Comment by CPapadim** [comment]
Ok, thanks for the info, I will switch away from using the Taxonomy field option for now.

**Comment by jimtrue** [comment]
If you need taxonomy, definitely use taxonomy. You know you need Taxonomy instead of a relationship if the purpose of this field is to filter, group or in other ways can't exist by itself as a single post (ie it can't exist as a sole piece of data, it can only exist as other 'items that are flagged this way'

**Comment by jimtrue** [comment]
I will let @pglewis and @sc0ttkclark weigh in on the 'taggable' not acting as intended because as I understand, we're doing away with that option.

**Comment by pglewis** [comment]
This is back on the 2.7 list, I think we still need to support this

**Comment by JoryHogeveen** [comment]
Just tested this on 2.6.11 and it also doesn't work (CPT > rel_meta > Tags). Not sure when it actually stopped working.

**Comment by pglewis** [comment]
This should be ironed out in #4601/#4602
