### ISSUE TITLE
Navigate Single Pod Admin not working

### ISSUE THREAD

**Issue by anthonyhuwng** [pods-framework/pods#4576]
Hi there, I have a problem with POD

When I edit a single pod on admin, there is a Navigate option to view next and previous single post.But it is not working.For the first time, I click next link it works.

But keep going to next I see it ends. Start from the start. It only goes to the right about 6 times.

Also when I click on the Previous link, it always takes me to the latest pod.

**Comment by jimtrue** [comment]
@anthonyhuwng I've never seen a navigate to next or previous post in the back-end Admin. On the front-end in the Theme, sure, but never on the back-end. What theme are you using?

**Comment by anthonyhuwng** [comment]
Hi Jim, thanks for your repsonse.

I used the default theme. 

Please check the screenshot [![Screenshot from Gyazo](https://gyazo.com/bbf633af6b3c946106b980cecda92824/raw)](https://gyazo.com/bbf633af6b3c946106b980cecda92824)

**Comment by jimtrue** [comment]
Now I know why I've never seen that @anthonyhuwng **Is this an Advanced Content Type?** Navigate isn't an option in regular WordPress on the edit posts screen.

How many posts do you have?

**Comment by anthonyhuwng** [comment]
@jimtrue Yes, It is an Advance Content Type.

I have about 200 posts.

**Navigate isn't an option in regular WordPress on the edit posts screen.** => I am not sure what you mean.

**Comment by anthonyhuwng** [comment]
I am talking about the POD framework. Please notice that **It is a POD**, not custom post type or default posts of WP.

**Comment by jimtrue** [comment]
Navigate in the edit screen isn't available for regular WordPress posts, that's why I needed the clarification. I've never personally seen it before because I don't tend to work in Advanced Content Types that often. 

I'm kicking this up the chain to @sc0ttkclark or @pglewis because the Navigation properties don't work on the same methodology as they do in WordPress and they'd be better able to identify if this is a bug or if there's something you need to do to properly navigate the screens in your Advanced Content Type.

BTW, 'Pod' is just our vernacular: it's what we use to say a 'Content Type', whether that's a Custom Post Type, Taxonomy, Settings Page, Extended WordPress Object or an Advanced Content Type.

**Comment by anthonyhuwng** [comment]
Ok, thank you for your support.

I hope other guys can solve this issue.

**Comment by menelas** [comment]
Any reply? I'm having the same issue...

**Comment by quasel** [comment]
works for me now! 

Sorry for the late reply, feel free to comment if you still have questions!
