### ISSUE TITLE
Image field don't show in template after upgrade Pods

### ISSUE THREAD

**Issue by lunacroft** [pods-framework/pods#4630]
After upgrade Pods to last version, images don't show in single.php page. I am using this magic tag: `{@galeria._img.139x93}`.

Post thumbnail is working, but field upload file/image/video is not working.

**Comment by jamesgol** [comment]
Can you share more of your code that is calling this?  Is it within a [pods] shortcode, an [if] or [each] tag?

**Comment by jimtrue** [comment]
@lunacroft We requested more of your code so we could help troubleshoot this issue. Since you haven't responded in over a month, I'm going to assume you are no longer having this issue. If you still are, please re-open this issue with your code sample as requested so we can help troubleshoot.

Thanks!

**Comment by lunacroft** [comment]
My code:

`[if galeria]
	<div class="jcarousel-wrapper">
		<div class="jcarousel">
			<ul>
			[each galeria]
				<li>
					<a href="{@galeria._src.large}" data-elementor-open-lightbox="yes" data-elementor-lightbox-slideshow="tni6pq4">
						{@galeria._img.139x93}
					</a>
				</li>
			[/each]
			</ul>
			<a href="#" class="jcarousel-prev">‹</a>
    		<a href="#" class="jcarousel-next">›</a>
		</div>
	</div>
[/if]`

This code is working in Pods version 2.6.11.

**Comment by jimtrue** [comment]
@lunacroft You've got a syntax error that 2.6.11 was more _forgiving_ about. See our [Template Tags in Pods Templates](https://pods.io/docs/build/template-tags-in-pods-templates/). Specifically when you do an `[each field_name][/each]` loop, you don't repeat `{@field_name` inside the loop, because you're actually looping through that field, so you only include the `{@_img.` etc. from that point on. To correct your code, you'd use:

```
[if galeria] <div class="jcarousel-wrapper"> <div class="jcarousel">
<ul>
[each galeria]<li><a href="{@_src.large}" data-elementor-open-lightbox="yes" data-elementor-lightbox-slideshow="tni6pq4"> {@_img.139x93} </a></li>
[/each]
</ul> <a href="#" class="jcarousel-prev">‹</a> <a href="#" class="jcarousel-next">›</a> </div> </div>[/if]
```

**Comment by jimtrue** [comment]
Try the above code change @lunacroft and see if that works for you ;)

**Comment by lunacroft** [comment]
@jimtrue  I'll try it, thanks!

**Comment by jimtrue** [comment]
@lunacroft Y'welcome and good luck!!

**Comment by lunacroft** [comment]
@jimtrue it works! Thanks a lot =)
