### ISSUE TITLE
Large number of update_meta_cache queries

### ISSUE THREAD

**Issue by CPapadim** [pods-framework/pods#4676]
I'm trying to reduce the number of queries for a query that includes many results (~1000).  

I'm using 'select' to reduce the number of queries down to 12 total for the pages, which works great.

However, every few minutes a page refresh will cause pods to execute ~1000 update_meta_cache queries.  I'm interested in either removing these, or increasing the length of time between when this happens.  How can I go about doing that?

**Comment by sc0ttkclark** [comment]
This looks like you're running out of object cache memory, so it dumps it and fills the cache again. Are you using Pods Alternative Cache?  That could help offload some of Pods' caching itself, while letting WordPress does what it does for it's own caching stuff (update_meta_cache etc).

You also might consider using the `cache_mode` and `expires` options in find() to cut down on more queries https://pods.io/docs/code/pods/find/

**Comment by CPapadim** [comment]
I am using pods alternative cache.  What triggers the clearing of the cache in this case?  I did play around with those cache settings but it didn't seem to make a difference what time I used for 'expires'.

**Comment by sc0ttkclark** [comment]
update_meta_cache is a WP object cache thing, do you have object caching enabled for your site? Are you using a caching plugin for that?

**Comment by sc0ttkclark** [comment]
Pods Alt Cache only covers Pods' stuff, we don't interfere with the normal caching within WP (separating the two can really help both excel, based on performance testing I've done)

**Comment by CPapadim** [comment]
I investigated this a bit more.  Using query monitor it suggests pods is responsible for the queries, and here's a trace:

```
Pods->display()
wp-content/plugins/pods/classes/Pods.php:585

Pods->field()
wp-content/plugins/pods/classes/Pods.php:1063

get_metadata()
wp-includes/meta.php:497

update_meta_cache()
wp-includes/meta.php:826
```
This is the type of query that's being run

`SELECT post_id, meta_key, meta_valueFROM wp_postmetaWHERE post_id IN (17411)ORDER BY meta_id ASC`

If I entirely remove object-cache.php, these queries will always happen on each page load, but with object-cache.php they happen once every so often.

I also tried disabling wordpress cache in the wp-config.php by setting define('ENABLE_CACHE', FALSE); but this doesn't seem to have any effect one way or another.

**Comment by sc0ttkclark** [comment]
After further looking into this, I'm pretty sure there's not a way around this because `get_post_meta()` / `get_metadata()` calls will trigger this naturally with no way to work around that.

1. First steps to deal with this should involve contacting the host and finding out if the object cache is properly set up for the environment.
2. Then make sure the site has enough object cache storage available to it for use.
3. Then look at Pods Alternative Cache to help segment our Pods-specific caching from the normal object cache to see if that helps reduce object cache usage.
4. And finally, to disable meta caching requests entirely, you can always `add_filter( 'update_post_metadata_cache', '__return_false' );`

It's better not to void the whole post metadata caching process because if you see this issue it's a sign that something else is going on with the server environment.
