### ISSUE TITLE
Backend - overlapping fields from middle (contents) columns disable right column actions (e.g. Update)

### ISSUE THREAD

**Issue by Brian-Milnes** [pods-framework/pods#4700]
When you are editing a post, if you use a narrow Windows pane (such as the auto-half screen), the WordPress "middle column" edit boxes may "overlap" the right hand column and suppress the operation of contents therein. (Like Update, Move to Bin, or Category seleciton)

These images from TwentySeventeen Theme (responsive front and back end)

![image](https://user-images.githubusercontent.com/28740085/34651967-e49de824-f3cf-11e7-9f8d-863961b7dbd5.png)

![image](https://user-images.githubusercontent.com/28740085/34652006-738331de-f3d0-11e7-8652-e7eb58965c64.png)

**Comment by Brian-Milnes** [comment]
Thanks for picking up on this @sc0ttkclark  Discovered a pretty bad/worst case scenario with an Autocomplete field having such a long input, that, without any wordwrapping or right margin/boundary, it pretty much disables saving an edit.
![image](https://user-images.githubusercontent.com/28740085/34839099-679d7656-f6f8-11e7-905f-37d28ba8ba95.png)
"Guilty" field on a full width on a 1920 px monitor:
![image](https://user-images.githubusercontent.com/28740085/34839185-9c08645a-f6f8-11e7-9487-d42f1ac5321a.png)

**Comment by sc0ttkclark** [comment]
Appreciate the feedback, we'll get this fixed and cleaned up.

**Comment by jimtrue** [comment]
I'm wondering how you would be able to 'cut' the content of that one post-title so it _could_ wrap. I just noticed that one of your items in your list that is overlapping was one _incredibly_ long post title. Since that's considered all one block for drag and drop in the Select2, I'm not sure if the AutoComplete can allow a block to 'wrap' within itself; @nicdford is that a possibility?

**Comment by nicdford** [comment]
This is what I was wondering from a usability perspective. I'll do some digging, but I think wrapping the text instead of having it cut off at a certain width with might be our best option.

**Comment by Brian-Milnes** [comment]
' .postbox table.form-table{ table-layout: fixed; } '

**Comment by nicdford** [comment]
Thanks @Brian-Milnes i'll get a commit made up for this shortly

**Comment by nicdford** [comment]
After doing a bit of digging, I believe WooSelect is limiting what we can do with regards to UX (scrolling/wrapping items instead of just one big long line of text). I've done my best with just CSS at the moment, but I think i'll need to dig into the JS to see what SelectWoo is doing to calculate height or if they're setting the height with JS or something like that. Anyway, the fixes with regards to width, should be addressed in a PR i'll have up tonight once some other blockers go through.
