### ISSUE TITLE
Editing Pods Records in backend - cursor jumps to first Autocomplete field

### ISSUE THREAD

**Issue by Brian-Milnes** [pods-framework/pods#4725]
When you edit a Pod CPT record in the backend, the cursor irritatingly jumps to the first Autocomplete field.

In a big CPT this can take some time to return to where you wanted to be, and the expectation is that you'll be in the first field.

**Comment by lougreenwood** [comment]
👍 - I've noticed this too

**Comment by jimtrue** [comment]
Sounds related to/identical situationally to #4703

**Comment by Brian-Milnes** [comment]
Any chance of getting this bumped up the to-do-list, please?

My users have a whole load of data to enter in a long Pods CPT - and this behaviour is really annoying when it is happening at each entry or Update, when that's your "task for the day". (It's particularly irksome as it doesn't happen until right to the end of the page load.)

**Comment by Brian-Milnes** [comment]
Hi @nicdford 
I am just back after a late evening (1:30 am here)
It will probably be better to give you a login to duplicate site that you can experiment with at your leisure.
I'll sort that out in the morning or over the weekend.
Cheers
Brian

**Comment by jimtrue** [comment]
@lougreenwood Since you've also noticed this issue, could you provide a Pods Admin, Components, Migrate: Packages, Export JSON for us to test with? Part of the biggest issue in tracking down problems like these is being able to replicate them.

**Comment by pglewis** [comment]
I'm able to reproduce this with the package here: https://github.com/pods-framework/pods/issues/4504#issuecomment-341858761

The more complex "Package with a larger matrix of fields".

**Comment by GaryJones** [comment]
I imported the "Package with a larger matrix of fields" data from your link.

I created an `Issue 4504` post, added a title, nothing else, and published it. I went back into the list of `Issue 4504` posts and selected the one I just published. Nothing appears to be focused on page load, and the first press of the tab key gives focus to the Administrator checkbox in the User Roles Checkboxes field (first Pods field).

I CAN replicate the issue, by having at least one value selected in the User Roles Autocomplete field. On page load, the focus and cursor jumps to the User Roles Autocomplete field, and the first press of the tab key moves it on to the User Roles List View field which follows.

This happens on a narrow screen (on the desktop) as well. Unlike Chosen, Select2 doesn't appear to disable itself for narrow screen devices.

With JavaScript disabled, none of the pods-dfv-field data loads, so the problem doesn't exist (because the fields do not exist!).

Moving the empty User Caps Autocomplete field above the User Role Autocomplete, and the behaviour stays the same - the focus is kept on the populated User Role Autocomplete.

Interestingly, when the User Caps Autocomplete is populated, the new page load _still_ moves focus to the User Roles Autocomplete field - **it is not on the first autocomplete field that gets focus**.

The only difference between the two autocomplete fields is that they have a relationship to different entities - one is a relationship to User Roles, one is a relationship to User Capabilities.

If I duplicate the User Roles Autocomplete field and keep it at the bottom, the first instance retains focus on page load.

If I move that copy (ID 279) to the top, then the original field (ID 264) still retains focus on page load. If I delete the original, then the User Caps Autocomplete (ID 268) get the focus on page load. Suggests that **it's the lowest ID autocomplete field that gets focus**.

**Comment by GaryJones** [comment]
In `selectWoo.js`, there this [line](https://github.com/pods-framework/pods/blob/644e910adf240efae13e20fd26b0242fa5427fe2/ui/js/selectWoo/selectWoo.js#L1735):

```js
self.$search.focus();
```

There are other `$search.focus()` instances as well, but removing this line in `selectWoo.js` (with `SCRIPT_DEBUG` enabled) stops the focus jumping on page load.

Here's a quick capture showing the field not focusing after the code is removed.

![autocomplete-select-bug](https://user-images.githubusercontent.com/88371/41061615-1651f0c4-69cb-11e8-81c2-261eae8e9128.gif)

Obviously, amending selectWoo is undesirable. The focus call is made within a conditional:

```js
    // Return cursor to search field after updating.
    // Needs 1 ms delay because of other 1 ms setTimeouts when rendering.
    if ('undefined' !== typeof this.$search) {
      setTimeout(function(){
        self.$search.focus();
      }, 1);
    }
```

Here, `$search` refers to the `<li>` with the `<input>` inside of it - a key part of the autocomplete functionality, so as long as it's been added to the page, at least for a MultipleSelection.prototype that gets updated, then it looks like it will be focused.

[Another part](https://github.com/pods-framework/pods/blob/644e910adf240efae13e20fd26b0242fa5427fe2/ui/js/selectWoo/selectWoo.js#L2070-L2072) that does a similar focus, is this:

```js
    if (searchHadFocus) {
      this.$search.focus();
    }
```

Adding this to the MultipleSelection update logic works as well:

<details>

Note the two instances of `searchHadFocus`.

```js
  MultipleSelection.prototype.update = function (data) {
    var self = this;
    this.clear();

    if (data.length === 0) {
      return;
    }

    var $selections = [];

    for (var d = 0; d < data.length; d++) {
      var searchHadFocus = this.$search[0] == document.activeElement;
      var selection = data[d];

      var $selection = this.selectionContainer();
      var formatted = this.display(selection, $selection).trim();

      $selection.append(formatted);
      $selection.prop('title', selection.title || selection.text);

      $selection.data('data', selection);

      $selections.push($selection);
    }

    var $rendered = this.$selection.find('.select2-selection__rendered');

    Utils.appendMany($rendered, $selections);

    // Return cursor to search field after updating.
    // Needs 1 ms delay because of other 1 ms setTimeouts when rendering.
    if ('undefined' !== typeof this.$search && searchHadFocus) {
      setTimeout(function(){
        self.$search.focus();
      }, 1);
    }
  };
```
</details>

At this stage, I'd suggest that this is an upstream bug, that needs the fix applied in the Details, but...

Pods currently uses selectWoo 1.0.1. However, when we look at the selectWoo releases, we see this:

> "Fixes some focus issues found in previous releases of selectWoo."
 - https://github.com/woocommerce/selectWoo/releases/tag/1.0.2

Here are [the changes](https://github.com/woocommerce/selectWoo/compare/1.0.1...1.0.2).

One, in particular, stands out: https://github.com/woocommerce/selectWoo/commit/276899e91bc4af7b7a2235e17e4d27a61bd2a5a5

I'll update my local code to use 1.0.2 and report if that fixes things.

**Comment by GaryJones** [comment]
I copied https://raw.githubusercontent.com/woocommerce/selectWoo/1.0.2/dist/js/selectWoo.js to overwrite my local `wp-content/plugins/pods/ui/js/selectWoo/selectWoo.js`, force refreshed a few times to make sure, and yes, it seems to stop the issue.

So, there should be a PR that updates all selectWoo references to 1.0.2 (from 1.0.1).

**Comment by pglewis** [comment]
> So, there should be a PR that updates all selectWoo references to 1.0.2 (from 1.0.1).

I'm looking into that very thing right now.

**Comment by pglewis** [comment]
PR: #5004

**Comment by Brian-Milnes** [comment]
Thanks for issuing the updated version, guys. It has fixed the problem - no jumping to the AutoComplete field!
(y)

**Comment by pglewis** [comment]
Yeah, this one was really annoying when you get bitten by it.
