### ISSUE TITLE
Custom Pod field doesn't show without the delete_users user capability

### ISSUE THREAD

**Issue by carterlando** [pods-framework/pods#4754]
I'm having an issue displaying a pod field under a custom post type for a user without the delete_users capability.

I created the new field following these steps:
Add new pods > extend existing > selected "Pros" post type > added a relationship field that relates to the country taxonomy

And the field displays like a country dropdown for the selected post type.

Issue appears when editing user capabilities using the "Members" plugin: https://wordpress.org/plugins/members/

Without it the field it's visible to admin accounts.

I duplicated the Admin User Role, made sure it had all capabilities except delete_users and called this new role Developer.

With the Developer role which is basically an admin account that can't delete users, the pod field is not visible in the backend anymore.

**Comment by carterlando** [comment]
Hi,

Is there any follow-up on this?

**Comment by jimtrue** [comment]
We'd need to get your configuration to replicate this issue to troubleshoot why it's happening. Where is your "Pros" post type coming from and is your Country taxonomy created by Pods or something you're connecting from another post type? 

If you're trying to get a Taxonomy to work on another post type that isn't associated to it, making a relationship field to it is not the appropriate way. Under Advanced Options for your Taxonomy (if you created it with Pods) you can associate it to other post types. 

Also this might have to do with what is creating your Pros post type, since many people use the "delete_users" as a test for the Admin role. Is the post type part of your theme or another plugin?

**Comment by jimtrue** [comment]
How was this fixed @carterlando ?
