### ISSUE TITLE
"delete_users" capability seems to overwrite the Pods Advanced Content Type capabilities that are not enabled

### ISSUE THREAD

**Issue by apalfrey** [pods-framework/pods#4800]
## Issue Overview
We're creating an application that requires a new role and access to certain functionality within the wp-admin dashboard (manipulate users, posts, pages and specific pods). The role was created and given capabilities of an Editor with the required advance content type and WP functionality added. When adding the "delete_users" capability however, all advanced content types are displayed. Removing the "delete_users" capabilities (required functionality) has the desired effect minus the ability to delete users.

## Expected Behavior
The advanced content types with capabilities applied should be available along with the required WP capabilities (users, posts, pages, files etc.)

## Current Behavior
ALL advanced content types are available as well as the Pods Admin section (not enabled in the capabilities) see screenshots below (some details removed for some disclosure protection).

![pods-capabilities-no-delete-user](https://user-images.githubusercontent.com/10856428/37345153-2f7c8914-26c4-11e8-9bea-89c54306b428.png)
Pods Capabilities (minus delete_users)

![wp-no-delete-user](https://user-images.githubusercontent.com/10856428/37345190-4660d7de-26c4-11e8-85bf-57c3d4d19dfc.png)
Desired Effect (minus ability to delete users)

![pods-capabilities-delete-user](https://user-images.githubusercontent.com/10856428/37345231-59f16ab6-26c4-11e8-8f9b-13c277c61c7c.png)
Pods Capabilities (including delete_users)

![wp-delete-user](https://user-images.githubusercontent.com/10856428/37345253-68b26992-26c4-11e8-86e3-63e58a6a7de8.png)
Actual Effect (see additional advanced content types which should be hidden along with Pods Admin menu)

## Possible Solution
It appears that something with the "delete_users" capability overwrites the other pods capabilities for some reason.

## Steps to Reproduce (for bugs)
1. Enable "Roles & Capabilities", "Advanced Content Types" and "Table Storage"
2. Create more than 1 advanced content types using the table-based storage option
3. Create a new role
4. Give it the same capabilities as an Editor along with "edit_files" the user capabilities (minus delete_users) (i.e. "add_users", "create_users", "edit_users", "list_users", "promote_users", "remove_users")
5. Also give the new role the ability to edit, create and delete one or two advanced content types, but not all of them (e.g. "pods_add_content", "pods_edit_content" "pods_delete_content")
6. Create a new user with this role and see the result
7. Add the "delete_users" capability and see the result, you should see all advanced content types that should not be accessible are accessible.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
Debug Information
WordPress Version: 4.9.4

PHP Version: 7.1.15

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: know_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/mysite/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Simpods MVC Child

Currently Active Plugins:

Contact Form 7: 5.0.1
Contact Form CFDB7: 1.2.1
Duplicator: 1.2.34
Panda Pods Repeater Field: 1.2.0
Pods - Custom Content Types and Fields: 2.7.1
Post Types Order: 1.9.3.6
Really Simple CAPTCHA: 2.0.1
Toolbar Publish Button: 1.6
</details>

**Comment by luc122c** [comment]
I'm also having this issue, I can't figure out a work around other than manually re-coding the capabilities? Any chance of a fix?

**Comment by luc122c** [comment]
@pods-framework @jimtrue Is this bug going to be acknowledged?

**Comment by jimtrue** [comment]
@luc122c and @apalfrey This seems to be a very edge case issue. Sorry no one has responded to your report, but in some of these situations, recreating the issue can take longer than actually solving the issue. If you can (as we ask in our GitHub Issue template) providing a Pods Admin, Components, Migrate: Packages, Export can help greatly in getting your issues replicated and tested so it's faster and easier for one of our developers to provide a fix. By having limited resources, we are often forced to focus issues to the greatest percentage of users impacted (the needs of the many outweigh the needs of the few). 

I, personally, don't work with ACT so it's outside of my wheelhouse of troubleshooting typically. Once you also get into Roles & Capabilities with an external configuration that really doesn't play with WordPress common objects, you're working in areas where we often rely on our community developers to also help out with solutions since we are an open source project. 

If you're able to come up with a solution that deals with manually re-coding the capabilities, then that would be a fix that would more than likely work for everyone involved and that's an opportunity for you to submit a solution to fix the situation. We would greatly appreciate such an effort.

**Comment by quasel** [comment]
has to do with fall back and the way WordPress works more background information #3985 and closing in favor of #2311
