### ISSUE TITLE
Fatal error if not logged in and accessing wp-admin

### ISSUE THREAD

**Issue by tanthammar** [pods-framework/pods#4828]
## Issue Overview

I forgot to log in and tried to access wp-admin.
This caused a fatal error.

## Expected Behavior
No error

## Current Behavior
Fatal error: Uncaught Error: Call to undefined function get_current_screen() in /home/bokamark/staging.bokamarknad.se/wp-content/plugins/pods/classes/PodsInit.php:304 Stack trace: #0 /home/bokamark/staging.bokamarknad.se/wp-includes/class-wp-hook.php(286): PodsInit->register_assets(‘’) #1 /home/bokamark/staging.bokamarknad.se/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /home/bokamark/staging.bokamarknad.se/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/bokamark/staging.bokamarknad.se/wp-includes/script-loader.php(1435): do_action(‘wp_enqueue_scri...‘) #4 /home/bokamark/staging.bokamarknad.se/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts(‘’) #5 /home/bokamark/staging.bokamarknad.se/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /home/bokamark/staging.bokamarknad.se/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /home/bokamark/staging.bokamarknad.se/wp-includes/general-template.php(2614): do_action(‘wp_head’) #8 /home/bokamark/st in /home/bokamark/staging.bokamarknad.se/wp-content/plugins/pods/classes/PodsInit.php on line 304

## Possible Solution
Add an if-statement to check if user is logged in.
Update line 304 in Podsinit.php to;
if (is_user_logged_in() && is_admin()) {...}

## Steps to Reproduce (for bugs)
See issue Overview

**Comment by therealgilles** [comment]
I believe the better fix would be:

`if ( is_admin() && function_exists('get_current_screen') ) {...}`

**Comment by jimtrue** [comment]
@tanthammar and @therealgilles I'm actually not able to reproduce this error locally. If I attempt to access the wp-admin and I'm not logged in, I'm re-routed to the login screen. Is that not the case with your installations?

**Comment by jimtrue** [comment]
Additional forum post for reference from @therealgilles https://wordpress.org/support/topic/problem-with-ajax-requests/

**Comment by therealgilles** [comment]
In my case, I am using the login-with-ajax plugin. Therefore I am guessing that it's an ajax request that's creating the problem. When doing an ajax request, is_admin() returns true.

I also read this from the get_current_screen page:

`This function is defined on most admin pages, but not all. Thus there are cases where is_admin() will return true, but attempting to call get_current_screen() will result in a fatal error because it is not defined.`

So again I reckon it would be better to qualify the if statement by checking if the function is defined when the code is reached.

**Comment by pglewis** [comment]
PR: #4947
