### ISSUE TITLE
When using wordpress page instead of archive, pagination returns 404

### ISSUE THREAD

**Issue by ostryanyn** [pods-framework/pods#4914]
## Issue Overview
Use wordpress page instead of archive page

## Expected Behavior
A page with custom query to work instead of pods archive.

## Current Behavior
I have custom post type `country`. Archive page switched off. Url to single item is `/countries/slug`, also i have a page (not archive) `/countries`, `/countries/page/[2,3,...]` always return 404 error. I suppose there is some kind of conflict, if i rename slug of page to `/countries1/page/2` it works. Switching `Rewrite pages` from `Advanced options` doesn't change anything.

## Steps to Reproduce (for bugs)
1. Create pod `country`.  Custom slug `countries/...`
2. Create page `countries/`, add any query with pagination
3. countries/usa return pod item
4. countries/ returns first page of custom query
5. countries/page/[2,3,...] returns 404
6. renaming page slug to countries1/page/2 works

## WordPress Environment
<details>
```
WordPress Version: 4.9.5

PHP Version: 5.6.30

MySQL Version: 5.5.5

Server Software: Apache/2.4.29 (Unix) mod_wsgi/4.6.0 Python/3.4

Your User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: No
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: rcso_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/tgb/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: WP Bootstrap Starter Child

Currently Active Plugins:

    ACF Content Analysis for Yoast SEO: 2.0.1
    Advanced Custom Fields: 4.4.12
    Backup: 1.1.61
    Contact Form 7: 5.0.1
    Contextual Related Posts: 2.4.1
    iThemes Security: 6.9.2
    Pods - Custom Content Types and Fields: 2.7.2.1
    Profile Builder: 2.8.1
    Redirection: 3.2
    WordPress Popular Posts: 4.0.13
    WP Super Cache: 1.6.0
    Yoast SEO: 7.4.2
```
</details>

**Comment by ostryanyn** [comment]
Is i found countries/[country_name] is not working too, returns 404

**Comment by jdaviescoates** [comment]
I have what I think is a similar problem.

I want to use Breadcrumbs. In order for the breadcrumb links to exist/ work I need to have Enable Archive Page enabled in advanced. But then of course when clicking on the link in the breadcrumbs I get taken to the archives page when I actually want to be take to my page with the same URL.

My pod is called Apps
Label: App
Singular label: App

I noticed that when I have Enable Archive Page enabled I can get to the page I want by going to https://selfhost.cloud/Apps/ rather than https://selfhost.cloud/apps/ and so I've managed to create the set-up I want be using Redirection plugin to re-direct https://selfhost.cloud/apps/ to https://selfhost.cloud/Apps/ but ideally I'd like to achieve the same result without the redirect - possible?

You can see what I'm talking about at https://selfhost.cloud

**Comment by JoryHogeveen** [comment]
You cannot use a page as a post type archive. This is something WordPress core handles this way.

I happen to know of a plugin that kinda overwrites this called "Page for Post Type".
It cannot be found on the WordPress.org repository but on GitHub only and it's not actively maintained: https://github.com/humanmade/page-for-post-type
I cannot advice you to use it if you do not have any knowledge of WordPress core and general programming.

**Comment by jdaviescoates** [comment]
Thanks, I may take a look at that plugin, but I'll likely just stick to my redirect solution for now.
