### ISSUE TITLE
Accessibility: DFV

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#5003]
With the DFV field expansion poised to explode we need to determine all the accessibility needs of our fields and make sure it's implemented.  The initial conversion of pick and file upload just mimic most of the markup of the old fields without any audit for accessibility.  I want the 2.8 DFV fields to be accessibility-minded from day one.  

Any expertise in this area is much appreciated, I'm going to be learning the ropes on the fly.

**Comment by leepeterson** [comment]
@pglewis I have quite a bit of experience with accessibility dating back to my days working for DoD and other government contracted companies, circa 2005-2007. A large part of my roles since then has focused on UX (before UX was the "thing" that it is today), and accessibility is one of my primary concerns when designing, developing, etc. Perhaps I can be of some assistance. 

Question: what does `With the DFV field expansion poised to explode` mean? Is there a related issue I can reference?

**Comment by pglewis** [comment]
> Question: what does With the DFV field expansion poised to explode mean?

"Dynamic Field Views" are the name of the new MV* based, client-side built fields, currently just pick (relationships) and file upload.  All remaining fields will be converted as part of 2.8 and there is an issue per field on the 2.8 milestone (eg #4662).  

This is a perfect opportunity to audit all the field markup for accessibility as well as streamline classes/CSS and other areas.

**Comment by pglewis** [comment]
https://developers.google.com/web/fundamentals/accessibility/how-to-review

**Comment by sc0ttkclark** [comment]
Accessibility addressed in Pods 2.8 React work, more work will continue in that area.
