### ISSUE TITLE
Enhancement: total and total_found magic tag

### ISSUE THREAD

**Issue by misspato** [pods-framework/pods#5039]
**Pod Count Tag**
It would be very useful to have a tag to show the total items on a given pod. For example, in a Pod named Book, there could be a {@books-total} tag that could be used to display the total amount of books.

## Tasklist

- [x] Define special magic tag name for total and total found
- [x] Add logic for `total` (or whatever we name it) that returns `$this->total()`
- [x] Add logic for `total_found` (or whatever we name it) that returns `$this->total_found()`

**Comment by jimtrue** [comment]
The problem with using this as a magic tag (ie `{@count}` ) is that tags are used at the post level, not at the 'pods' level:

`{@count}` against a Taxonomy, Related Field or File/Media/Upload field to return the 'count' of those items, makes sense, because they are an associated array from the current post, so either `{@taxonomy-type.count}` or `{@related_field.count}` would return the count of the items related to the current post.

For a Books 'total' that should really be a shortcode option, called as a parameter, maybe pulling in the functions that already exist in Pods `total` and `total_found`.

@sc0ttkclark @pglewis thoughts?

**Comment by soulwasted** [comment]
How far is this with planned release...? Thanks.

**Comment by jimtrue** [comment]
@soulwasted It's scheduled for the next release, 2.7.7

**Comment by pglewis** [comment]
PR: #5042

**Comment by andrepetrini** [comment]
Hi guys, any news about that? Is it possible already or do you have a planned release?

**Comment by sc0ttkclark** [comment]
@andrepetrini this is now scheduled for Pods 2.8 and is already in the current beta. We are working hard on testing the rest of 2.8 to make sure it's stable for release -- I don't have an ETA on that unfortunately.
