### ISSUE TITLE
Upgrade to 2.7.6 crashes wordpress site

### ISSUE THREAD

**Issue by CCC-better** [pods-framework/pods#5058]
## Issue Overview
I have had 2.2 for ages (after starting with v1) and finally upgraded to 2.7.6 tonight. The result is a wordpress site that crashed - it delivered a blank page with no content when viewing the page source. There are no error messages - just a blank (empty) page. 

UPDATE: upgraded to 2.5.1.2 without a problem

## Expected Behavior
A smooth upgrade

## Current Behavior
As above.
I have tried checking other plugins, but it is the upgrade to pods 2.7.6 that causes the behaviour (thank God for a wonderful webhost with daily backups)

The only thing I could find is in the error log:
2018-07-10 20:58:51.802817 [INFO] ...  File not found [/.../public_html/404.shtml]
2018-07-10 20:58:51.802796 [INFO]  ... File not found [/.../public_html/]

## Steps to Reproduce (for bugs)
1. Login into wordpress
2. Open the plugins list
3. Accept the offer to upgrade to v. 2.7.6 from 2.2

Also tested by viewing the same blank page in firefox and chrome.

## WordPress Environment
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.

THIS IS FOR V.2.5.1 AS THE SITE WASN'T VIEWABLE WITH 2.7.6
<details>
```Debug Information
WordPress Version: 4.9.7
PHP Version: 5.6.36
MySQL Version: 10.2.15
Server Software: LiteSpeed
Your User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:3.4) Gecko/20100101 Goanna/20180610 PaleMoon/27.9.3
Session Save Path: /opt/alt/php56/var/lib/php/session
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
WPDB Prefix: wp_
WP Multisite Mode: No
WP Memory Limit: 40M
Pods Network-Wide Activated: No
Pods Install Location: /home/.../public_html/wp-content/plugins/pods-2.x-2.5.1.2/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Theme: Editors
Currently Active Plugins:
    CSE Editors Pods UI: 10
    Fast Secure Contact Form: 4.0.57
    Jetpack by WordPress.com: 5.3
    Members: 2.1.0
    Pods - Custom Content Types and Fields: 2.5.1.2
    WP Mail From II: 1.1
```
</details>

## Pods Package Export (helpful!)
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```
[pods2-5.2.txt](https://github.com/pods-framework/pods/files/2180169/pods2-5.2.txt)

```

## Workaround or Alternate Solution Until Bug is Addressed
Rollback to the last stable version - which was 2.2 in my case (now back to 2.5.1)

**Comment by CCC-better** [comment]
The comment history tells me Jim was trying to read this. Sorry. Will stop now!

**Comment by jimtrue** [comment]
@CCC-better I'm very very sorry to hear about the issues you're having. Other than that being an incredibly long wait on an update (2.2 was released way back in January of 2013, 5 years ago) the other thing I see in your installation that might be an issue is CSE Editors Pods UI. I've never heard of this plugin. Did you folks have something custom coded for Pods?

(And yep, I was cleaning up the issue report so it could be read. Your package export was huge ;))

Do you have a development or staging copy of this installation? If your host can do that (some do), anytime you're waiting that long on an upgrade, it's better to test it out on a Development copy rather than your live website. With you waiting 5 years to update Pods, that's pretty much a necessity, so you don't run into issues like the blank screen.

**Comment by jimtrue** [comment]
I'm thinking if that plugin CSE Editors Pods UI was written with some out of date code, that _might_ be your culprit. White screens of death as we call them in WordPress are usually due to some PHP debug issues. You can also route down the culprit or at least get additional details by adding the debugging strings to your websites wp_config.php file from https://codex.wordpress.org/Debugging_in_WordPress

Typically, you only want to do that on Development copies.

**Comment by jimtrue** [comment]
@CCC-better Okay I also just saw you were able to get to 2.5.1.2, correct?

**Comment by CCC-better** [comment]
Correct. Should I try 2.6?

The CSE Editors Pods UI is a blast from Pods 1. It works and I'm reluctant to change it.

**Comment by jimtrue** [comment]
Yep, a staged approach to upgrading to see what might be breaking is always better. If you've got the dev version, it's a lot easier to test the issues with the upgrades.

Is the CSE Editors Pods UI a homegrown plugin? I'm not finding it out on any of the repo's. If it's from 1.x it would've had to be upgraded to work on 2.2 as well.

**Comment by CCC-better** [comment]
The CSE Pods UI plugin was how we did Pods UI back in the 1.0 days. it wasn't upgraded as far as I remember and it continued to just work. I've attached it here (note that I've changed the extension from php to txt so I can upload it).
[editors-ui.txt](https://github.com/pods-framework/pods/files/2180287/editors-ui.txt)

**Comment by CCC-better** [comment]
And I've managed 2.6.1 as well, while I'm here. So at least I'm less than half a decade behind now!

**Comment by CCC-better** [comment]
And now 2.7.1 was successful. I think I can live with that until another day. Thanks for your help so far.

**Comment by jimtrue** [comment]
Awesome! And Congratulations! Get some sleep ;)
