### ISSUE TITLE
Polylang Media Files

### ISSUE THREAD

**Issue by vogttho** [pods-framework/pods#5060]
**Describe the bug**

**To Reproduce**
1. Install Polylang and Pods
2. Create Pods Page extension to Upload Media Files
3. Create a Page and upload 1 pdf file 
4. use translation options in the right menu to create a translated page
5. Upload 1 pdf file to the translated page

The file is not visible. More Fields is empty. But the files are there and I can make them visible if I change to the translated language in the topmenu language dropdown.

**Expected behavior**
See the uploaded file on the translated page in More Fields.

## Pods Version
WordPress Version: 4.9.7
PHP Version: 7.2.7
MySQL Version: 10.1.34
Pods - Custom Content Types and Fields: 2.7.6
Polylang Pro: 2.3.7

**Possible Workaround**
If you change to show all languages. Or I can see it if I enable screen options - custom fields. 

It happens only with Media files. Other types like plain text work as expected.

**Comment by JoryHogeveen** [comment]
I think the following is happening:

Since you've selected a language in the dropdown, Polylang is automatically assigning that language to the uploaded file (no matter the post language you are currently in).
Pods <> Polylang compatibility checks the current dropdown (general language) but this get's overruled with the current (being edited) post language. Pods tries to find related files with that language and can't find any since the file that was uploaded got the general language, not the post language.

I will try to replicate and let you know!

**Comment by JoryHogeveen** [comment]
Issue reproduced.
The problem is with checking the current screen.
In my tests this doesn't return any `WP_Screen` object check getting the current language.
Pods _should_ get the current language of the current object when editing posts or taxonomies but it checks this based on the current screen.

I have no clue why the current screen doesn't return anything.
@sc0ttkclark @pglewis does this ring any bells?
Another solution would be to just check the `$_SERVER / $_GET` parameters instead of using `WP_Screen`

**Comment by pglewis** [comment]
> I have no clue why get_current_screen() doesn't return anything.

From the codex page for `get_current_screen()`: `The function returns null if called from the admin_init hook. It should be OK to use in a later hook such as current_screen.`  

Is it being called from `admin_int`?  If so, can we push that check until later?

**Comment by JoryHogeveen** [comment]
PR done, see: #5064

**Comment by JoryHogeveen** [comment]
> From the codex page for get_current_screen(): The function returns null if called from the admin_init hook. It should be OK to use in a later hook such as current_screen.
Is it being called from admin_init? If so, can we push that check until later?

It is called multiple times in the codebase, before and after `admin_init`. Still, this used to work fine.
In the PR I removed the `get_current_screen()` reference and used `basename( $_SERVER['SCRIPT_NAME'] )` to get the current screen base.
