### ISSUE TITLE
pods admin - cache problem

### ISSUE THREAD

**Issue by intellinet-online** [pods-framework/pods#5094]
my website is: danzigeronline.com
1. i installed pods admin and i created Custom Post Type named "growers"
2. i implemented the CPT in this page: https://danzigeronline.com/growers/
3. each cpt has the following fields see attached picture
4. sometimes (there is no exact rule for this) the logo+varieties disappear,  and only after i "Clear Pods Cache
clear all of the transients/cache that are used by Pods. "
everything comes back to normal after 5-15 minutes

a. it's probably a cache problem inside pods so how to disable it?
b. how can you help me with this?
![image](https://user-images.githubusercontent.com/42240459/43897423-97ed3af8-9be4-11e8-8ea9-e7f6525cc90b.png)

# Adding Debug Details that were left off but posted on Slack Chat
<details>
```
Debug Information
WordPress Version: 4.9.8

PHP Version: 7.0.31

MySQL Version: 5.5.5

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/danziger/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Bridge Child

Currently Active Plugins:

404page - your smart custom 404 error page: 6
Addons for Visual Composer: 1.8.2
Admin Taxonomy Filter: 1.0
Advanced Custom Fields PRO: 5.6.10
Advance Tabs for Visual Composer: 1.0
Argi Custom Wishlist: 1.0.0
Change Taxonomy Buttons: 1.0.1
Cloudflare: 3.3.2
Composium - Visual Composer Extensions: 4.2.4
Compress JPEG & PNG images: 2.2.6
Contact Form 7: 5.0.2
Contact Form 7 MailChimp Extension: 0.4.50
Contact Form CFDB7: 1.2.2
Cool Timeline: 1.4
Custom Content by Country (from iControlWP): 2.18.170521
Custom Hamburger:
Custom Post Type Permalinks: 3.2.2
Default Post Tags: 2.0
Duplicate Post: 3.2.2
Easy HTTPS (SSL) Redirection: 1.9
Envato WordPress Toolkit (Deprecated): 1.8.0
FeedWordPress: 2017.1020
GeoIP Detection: 2.8.2
Google Tag Manager for Wordpress: 1.8.1
LayerSlider WP: 6.5.1
LiteSpeed Cache: 2.3.1
Max Mega Menu: 2.4.2
Modal Window: 3.2.1
P3 (Plugin Performance Profiler): 1.5.3.9
PDF Embedder: 3.1.8
Pods - Custom Content Types and Fields: 2.7.6
Pods Alternative Cache: 2.0.2
PopAd: 1.0.4
Popup Builder: 2.6.7.6
Qode Instagram Widget: 1.2
Qode Quick Links: 1.0
Qode Twitter Feed: 1.1
Quick Page/Post Redirect Plugin: 5.1.8
Redirection: 3.3
Regenerate Thumbnails: 3.0.2
Relevanssi: 4.0.10.1
Shield Security: 6.8.2
Shortcode Widget: 1.5.1
Simple History: 2.26.1
Slider Revolution: 5.4.2
Static Block: 2.1
String Locator: 2.3.0
Tabs Responsive: 1.8.4
Tagboard Embed Shortcode: 0.3
Taxonomy TinyMCE: 2.0
Timetable Responsive Schedule For WordPress: 3.8
TinyMCE Advanced: 4.7.11
Ultimate Addons for Visual Composer: 3.16.3
Ultimate Member: 1.3.88
Ultimate Member - Social Login: 1.3.5
User Role Editor: 4.43
Users by Date Registered: 1.0.3
WonderPlugin Carousel: 12.5
WonderPlugin Lightbox: 6.1
WordPress Carousel: 1.4.7
Wordpress Image Mapper: 2.7
WPBakery Visual Composer: 5.1.1
WP File Manager: 2.8
WP Mail SMTP: 1.2.5
WP Migrate DB: 1.0.2
WP Testimonials with rotator widget: 2.2.6
WP Video Lightbox: 1.8.5
Yoast SEO: 7.6.1
```
</details>

**Comment by jimtrue** [comment]
@intellinet-online You brought this question onto Slack Chat before posting over here, so I'll respond with what I responded with over there.

"everything comes back to normal after 5-15 minutes" sounds like a Caching issue, definitely. When you posted this on Slack Chat, you included the Debug list (which is part of the bug report that you skipped), so I added it to your report above.

I see you have Pods Alternative Cache installed. Typically we don't recommend people install that unless there is a need to do so, so I would suggest disabling it. Also check your Host Server Configuration and check to see if they are running any Object Caching that is overly aggressive (putting gaps between when writing to the database) or at least see if you can flush it after creating fields, because once you've created them, they should be in the configuration unless one of your other plugins is stepping on the configuration.

You have a LOT of plugins installed on this website, several of which appear to create their own post-types. Start looking for conflicts. The standard method of this (which is given to most people to troubleshoot plugins) is to shut off all other plugins but the one that doesn't seem to be operating properly and see if it does by itself and then slowly add back plugins until it breaks. This isn't always possible if this is a live site, so you can install the Health Check & Troubleshooting (https://wordpress.org/plugins/health-check/) and it allows you to work in an instance of your server that only impacts _you_ and you can turn off and on plugins as needed to test.

**Comment by quasel** [comment]
We didn't hear back from you, I'm closing this!
Feel free to comment if you still have questions.
