### ISSUE TITLE
Block Editor Conversion for Shortcodes & Shortcode Wizard

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods#5239]
**Is your feature request related to a problem? Please describe.**
Not related to a problem; this is part of Gutenberg/WP 5.0 Block Editor compatibility. Converting our existing Shortcode Wizard into a Block or multiple blocks.

**Describe the solution you'd like**
Ideally, this should take advantage of the REST API to include field lookup from the Pods Object, so 2.8 might be a blocker. 

**Additional context**
This is a Starter Issue to include all the different things currently in the Shortcode Wizard and document what we're keeping/converting.

**Comment by patrikhuber** [comment]
Hi,

First of all thank you so much for developing and maintaining Pods, I just started using it and it's really fantastic.

I just watched the [introductory talk on YouTube](https://youtu.be/fxpH68u3sgw?t=2026) and the relevant part to this question is at 33:46 when the presenter uses the shortcode wizard to generate a custom list. I can see that the shortcode wizard is probably not yet available for Gutenberg. I found [this release announcement](https://pods.io/2018/12/05/pods-2-7-10-release-gutenberg-and-wp-5-0-compatibility/) from 2018 which details the status of Pods with Gutenberg and I subsequently found this issue. I hope this is the right place and issue.

Now it's 2020 and the WordPress world is pretty much Gutenberg-only, at least for new websites. Am I correct in assuming that the state of affairs in Pods with regards to custom shortcodes / wizard has not improved since that announcement and this issue in 2018?

1) In above linked announcement, there's a few recommendations in "_What We Recommend Before Updating_", namely to install the classic editor plugin. I was wondering if this was still up-to-date and now, in 2020, what would you advise would be the best way of generating/inserting a shortcode from custom HTML, like the presenter does in above video at 33:46, for a website exclusively built with Gutenberg?
Could I, for example, install the classic editor in a throwaway-environment (copy of the live site) just to use the wizard, generate the shortcode with the custom HTML template, and copy the result over to a Gutenberg Shortcode block on my live site?

2) Is there anything that could potentially help in speeding the development of this up? I am guessing manpower - but how far away is it? If 2.8 is a prerequisite, then this is probably not a matter of a dozen dev hours, but more like a couple hundreds?

Thanks a lot!

**Comment by sc0ttkclark** [comment]
We're currently finishing up our revisit to the Pods Blocks project right now. There were a number of challenges that the Blocks JS API has presented us with and we had other things to move forward with (Pods 2.8 Groups + structure refactor) at the time.

1. You can make custom shortcodes that returns content however you'd like. I've gotten into the habit of setting up all my logic in the function and calling a separate `include` to include the HTML markup I want so it's easier to maintain for myself that way. Keep in mind that shortcodes need you to return the content, not echo, so if you do an `include` then wrap it with `ob_start()` and `ob_get_clean()`.

```php
add_shortcode( 'your_shortcode', 'your_function' );

function your_function() {
	return 'Your custom content';

	// OR
	ob_start();
	include 'your-function-markup.php';
	return ob_get_clean();
}
```

2. Right now it's React knowledge and time that's left. We're nearly done with the JS side of what we needed, next steps are integrating what we've built with our reusable Pods block needs (List/single/etc) and then after that we'll be releasing an add-on that lets you build blocks from within the Pods interface.

This year has seen a big push from our team on multiple fronts. We're working hard to get things out the door to everyone.

**Comment by sc0ttkclark** [comment]
Pods 2.8 now includes Block conversion support in the new Pods Blocks PHP API and JS API. All of the Pods Blocks will now detect their associated shortcode / attributes and convert accordingly. 🎉
