### ISSUE TITLE
DFV relationships: Adding new items isn't done in correct order

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5515]
Original report: https://wordpress.org/support/topic/list-view-arrangement/
Second report: https://wordpress.org/support/topic/adding-items-to-relationship-field-changes-the-order-of-items/

**Describe the bug**
When adding relationships, for some reason all new items are added in (from the looks of it) alphabetical order, not the order in which the user adds them.

**To Reproduce**
1. Create a relationship field from Pages to Posts (other CTA are fine as well)
2. Add relationships randomly
3. You'll see that the order of the posts is not correct.

Even if you save the post and add new relationships afterwards, these new relationships start at the bottom but from then get added in the system order, not the order you add them.

## Pods Version
trunk

**Comment by sc0ttkclark** [comment]
I definitely think this isn't intentional. This specific view is powered by Backbone/Marionette, which needs to be refactored to React. That could be solved by the refactor in 2.8 or 2.9 -- but I'm not sure we could fix this easily outside of someone with deep knowledge knowing where to look/tweak. I gave it a review and it wasn't immediately apparent where the logic for adding to the collection could be going wrong.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen Can you confirm this works as expected in Pods 2.8 now? Note: There may currently be a separate issue where items are NOT showing up as expected in the relationship lists so this may have to be tested after that is fixed in https://github.com/pods-framework/pods/issues/5991

**Comment by sc0ttkclark** [comment]
Needs retesting

**Comment by pdclark** [comment]
Worked for me — List relationship selector keeps order saved and does not alphabetize.

<img width="1291" alt="Screen Shot 2021-09-16 at 3 11 51 PM" src="https://user-images.githubusercontent.com/126889/133692415-1036570d-1e89-4173-a8a4-daf688afb37e.png">
