### ISSUE TITLE
[Pods 2.8 UI] Field options checkbox location

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#5938]
Currently all field option checkboxes are shown below the labels. Might be better to show these on the left side of the labels.

**Comment by sc0ttkclark** [comment]
@JoryHogeveen Can you confirm this is resolved in `release/2.8`?

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Nope, checkboxes are still below the labels. See for example the "Required" option.

**Comment by sc0ttkclark** [comment]
In content forms, these are shown on as expected, but in the modal it's shown below due to the new interface of the modals.

<img width="310" alt="Screen Shot 2021-05-29 at 8 17 52 PM" src="https://user-images.githubusercontent.com/709662/120088910-10e82a00-c0bb-11eb-94aa-2cd39f1f7ed7.png">

<img width="818" alt="Screen Shot 2021-05-29 at 8 18 54 PM" src="https://user-images.githubusercontent.com/709662/120088916-1e9daf80-c0bb-11eb-9a60-3a6b15ad1c31.png">

**Comment by sc0ttkclark** [comment]
Just noting, we can still control whether text shows to the right of the checkboxes here, this is referring to the label / input layout

Some fields have `boolean_yes_label` set to empty on purpose

<img width="826" alt="Screen Shot 2021-05-29 at 8 22 57 PM" src="https://user-images.githubusercontent.com/709662/120088976-c87d3c00-c0bb-11eb-9207-5fe7233a6313.png">
