### ISSUE TITLE
Clear Pods DB garbage from wp_posts and wp_postmeta to own table(s)

### ISSUE THREAD

**Issue by justdudeone** [pods-framework/pods#6000]
Hello,

I already understand that the most web-developers at WP area, even of a such powerful project as Pods, are veeryyy faaaaar from the high quality DB architect standards. 

But when I create just 1 Pod with just 150 CustomFields your Pods make:
--- At wp_posts table (the most garbage WP DB table) records for EACH CustomField Description… Why??? Description is the simple 255 chars text, it must NOT be stored as wp_posts with all unneeded columns! Only to make the next linked garbage???…
--- At wp_postmeta table I found over 22’000 records of your Pods custom fields!!! 22’000 records for 150 custom fields!!! 
It's already not something to deal with!!! It's a mess!!! Does your team understand the conception of “DB CUSTOM TABLE” means DON’T USE DEFAULT tables?! I'm really shocked with such basic Pods DB architect problem!!!

**You really need to fix it by making your own standalone table to store Pods and Fields settings!**

So on Pods 2.8 install you really must resolve this problem by adding simple “DB update script” which will move all data from wp_posts+wp_postmeta to new correct and compact DB storing method:

- 1. Create 1 new table for all-in-one-record storing like “Pod #, Pod settings, All fields settings”, store settings as JSON. (As I found out this method is used by JetEngine, but it also not best).
- 2. Create 2 new tables for Pods and Fields, like “Pod #, settings” and “Field #, settings” store settings as JSON. 
- 3. Create 2 new tables for Pods and Fields but with individual columns for each settings, store settings at individual columns as clear text/numbers/values/etc.

For best accessibility and data clearance I would recommend method (c) it will also gives to other developers to get Pods/Fields settings directly from DB without need to parsing the huge JSONs. Empty columns at one record at (c) will add to overall DB size much less, than repeating list of all settings names at each record JSONs at (a,b).

Please, think wisely and answer - will you add this Pods fundamental problem resolving update to the Pods 2.8 or not? If not - I will prefer the much more accurate data storing at JetEngine.

You really must make it! Even the issue number confirms this 6000! :D

**Comment by justdudeone** [comment]
Guys, please, don't be offended. You make one of the BEST WP project and make it FREE - anyway you make a huge very good job and overall you almost like a Heros! :)

PS If you need more assistant with DB structure etc - I can help a little more with some advises etc. Maybe with overall project planning to make it easier for you to compete with JetEngine etc.

**Comment by lkraav** [comment]
Looking through the issues you filed

1. it's all known stuff, zero news - but highly difficult to refactor and solve
2. your presentation looks like a 7-year old's, of whom many probably even win in courtesy - "don't be offended"

> advises etc.

Most open source projects have enough advice, plans, known issues, etc.

Only thing that really matters is finding people capable of delivering Pull Requests.

I'd recommend skipping further theoretic advice, and filing that advice in PRs instead. That should illuminate much better what the actual problems are trying to refactor 10+-year old codebases. It's days and weeks of difficult work, which makes that one biggest difference between talkers and doers.

**Comment by justdudeone** [comment]
> it's all known stuff, zero news - but highly difficult to refactor and solve

Ouch, you can't create table and 1 procedure for code moving, and then just search through your not-very-complex project by notepad++ for auto replace all path and procedures... poor idiot...

> your presentation looks like a 7-year old's, of whom many probably even win in courtesy - "don't be offended"

Your face resembles the expression of a dog's muzzle when it voluptuously drunk shit of another dog and happily runs and taps.

**Comment by sc0ttkclark** [comment]
I'm reviewing this issue and will get back to you with more technical details on the issue you described as well as what we are doing in Pods 2.8 to make it possible to address.

**Comment by sc0ttkclark** [comment]
@justdudeone **We try to foster a welcoming and open community -- Your issues, comments, and other communication have been highly toxic. You have name called, used inappropriate language, and have been unnecessarily aggressive. This kind of behavior is not accepted in our community and it can easily put off people who contribute to our project from wanting to work on a potential bug fix, enhancement, or feature.**

**If you continue any further with this kind of behavior that violates our [Code of Conduct](https://github.com/pods-framework/pods/blob/main/docs/CODE_OF_CONDUCT.md), I will completely ban you from our GitHub. I will not warn you another time. Please use care and caution when you interact with our community or you will be not welcome to return. No exemptions will be made in our policy here -- but every one deserves a second chance. This is your second chance, please be mindful of our expectations here.**

---

Do you have some valid concerns in your issues? Yes, you do. See below for an outline of our plans here.

* #6000 - **Post/meta configuration bloat:** We are working working on a solution to solve the Post/meta problem with our configurations (we used to have a custom table) and that is now available to us as a pathway to complete with the work in Pods 2.8.
* #6001 - **If you are referring to Advanced Content Types here:** We do have a plan to expand the functionality of how this works and offering an Admin UI builder tool that is much more flexible and expansive.
* #6002 **Part 1 - Required boolean field:s** If a boolean field is marked as required, that means "No" or "0" will not be accepted as a valid value. That validation is handled at all areas of Pods from the admin interface to the API saving via code. 0 is not a valid value when you require a boolean (required: must be checked / 1). That's just how things work, you can totally make a boolean field save 0/1 but we do not have any plans to change how this works at this point.
* #6002 **Part 2 - Boolean fields saving "0":** This is something we will go back over and make sure is working as expected, it should be enforcing the 0/1 on save and if that's not happening we will get that resolved.
* #6003 **Part 1 - Simple Relationships data entry:** We have plans to expand our Simple Relationship interface with a cool set of fields where you can add/remove from the list. That takes time and work ($) but it will come in good time. We have other priorities like our major Pods 2.8 release which takes precedence over anything else right now.
* #6003 **Part 2 - Simple Relationships filtering:** We do plan on opening up the relationship filtering for simple relationships, this will take some time to finish as we have many other areas more important for us (see configuration bloat for example) which we plan on addressing ahead of areas like this.
* #6003 **Part 3 - Ratings field type:** We do plan on introducing some new field types in the future, but this is not a common request for us so we haven't had it prioritized. I will add this to our list of field types to expand to and see when we can get to that.
* #6003 **Part 4 - Comparison tables:** We don't have any comparison table kind of solution, but I would like to dig into this more deeply and figure out a way to offer vertical table views. I'm working on a Pods Pro List Table add-on and this would really compliment the feature set I'm building for that.
* #6003 **Part 5 - Project development processes:** These are all generalized things that we do when we are working on features, I'm glad we're on the same page here in knowing what we should be and are doing there. The shortcomings you mentioned come along for many different projects, it's something we will continue to work on as we develop Pods in the future -- to make sure it's getting better and more solid.

I also wanted to outline a few things as well, to make sure you are well aware of how Pods works and it's continued to stick around since 2008.

* We are a free plugin
* All of our code is released under GPLv2 and is provided as-is, without any warranty or implied warranty that it will server any/all needs that you have
* We accept [donations](https://friends.pods.io) and pool those donations together to pay @JoryHogeveen for his time on Forum/Slack support and also development of features, enhancements, and bug fixes -- and also for additional development contract support on features for Pods.
* We have free and open [WordPress support forums](https://wordpress.org/support/plugin/pods/)
* We have a free and open [Slack](https://support.pods.io/chat/)
* We have a free and open [GitHub](https://github.com/pods-framework) which contains all of our plugins and free add-ons available for Pods.
* We do our best to stay on top of WordPress support forums, Slack, and GitHub -- but members of our community some times step in to volunteer their help and expertise (you interacted with one of those people in one of the other GitHub issues that also violated our Code of Conduct).
* We are not pulling in gigantic amounts of donations and are not making more than we spend on maintaining the project on a month-to-month basis. This means that growth can be difficult and feature work can take extra time as I am the only person on the team who contributes features entirely unpaid.
* Please know that we are limited in resources and you simply cannot expect us to compete in the same exact way as other premium solutions out there. We do our best and I believe that we have gone far above and beyond any other free plugin out there in the amount of support we provide.

I wish you well and I hope your future work is successful. Whether that's using Pods or using JetEngine or ACF Pro or whatever it might be that fits your project needs most. I hope you will read over my feedback here and that it addresses your concerns appropriately.

I'm going to close this and your other issues as they are all duplicates of other existing issues in our GitHub.
