### ISSUE TITLE
Pods 2.8: broke compatibility with custom 3rd party fields

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6181]
## Description

The REACT UI is awesome but it fully broke all compatibility with custom 3rd party field types.
Just like WordPress created BC code for widgets etc. I think we should do the same for 3rd party field types (non REACT ui).

Maybe make a wrapper for jQuery or static field types that still use php templates (views).

**Comment by sc0ttkclark** [comment]
Should be OK, the only problem is calling DFV if the field type does not support DFV. As long as that doesn't happen, it should be fine. Link field type did this because I went over all field types to convert their inputs to DFV and forgot that the Link field type was not converted and was not a current field type in core.
