### ISSUE TITLE
Pods 2.8.x conflict with Yoast Duplicate Post plugin

### ISSUE THREAD

**Issue by TomSeltzer** [pods-framework/pods#6217]
## Description

It seems that the latest version of Pods has a conflict with the Yoast Duplicate Post plugin. It happened on two different sites of mine. On one, it caused a front-end error that took down the site. On the other, the front end worked, but I could no longer add or edit anything in a Pods-generated post type. Disabling Yoast Duplicate Post restored the site to full functionality in both cases. 

## Testing instructions

4. See error message '....'

## Other super helpful information

<details>
<summary>WordPress Environment</summary>
  
```
Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.
```

</details>

<details>
<summary>Pods Package Export</summary>

```json
Copy and paste your Pods Admin > Migrate: Packages > Export and paste the code over this line.
```

</details>

**Comment by WhyCry** [comment]
Does anyone else have issues with the Yoast Duplicate Post plugin with table-stored pods? It does not appear to be working on my site, only the basic data such as title/slug and relation fields are copied. Is there any working solution to "duplicate&edit" in 2.8.8 for table stored pods?

**Comment by JoryHogeveen** [comment]
Hi @WhyCry 

The Yoast Duplicate Post plugin doesn't support table based storage, only meta.

**Comment by WhyCry** [comment]
> Hi @WhyCry
> 
> The Yoast Duplicate Post plugin doesn't support table based storage, only meta. See #5434

Hi Jory thanks for the reply. 
I have seen this post but assumed it was old and no longer relevant. I have been using custom pods ui duplication and that worked great (custom page with 'action=duplicate'), but since upgrading to pods 2.8.8 I can no longer see and edit title/permalink/id fields, only pods-related fields (which are copied correctly). What this means is that when I duplicate the post and save it, it overrides existing pods. How can I display ID and title fields on such a page? If you are not planning to offer such a feature, how can I solve this quickly on my own?

**Comment by JoryHogeveen** [comment]
Hi @WhyCry 

Please open a new bug report for this and provide all information asked so we can get a better understanding of your exact installation, it seems like this is a different issue than this topic.
