### ISSUE TITLE
REST API depth for user relationships not working

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6260]
## Description

https://wordpress.org/support/topic/problem-with-custom-relationship-field-rest-api-2/

The results from the reporter and me are both different, not sure why..

Create a CPT with a relationship to users.
Set the REST Depth to 2.

My issue:
The REST API shows full user objects. Depth level is ignored.
Secondly, the key isn't the ID, should that be the case?

Reporters issue:
REST API only returns the user ID (as key AND value).

**Comment by JoryHogeveen** [comment]
Not sure what has changed but I cannot reproduce this issue anymore

**Comment by sc0ttkclark** [comment]
Some tweaks have been made to better ensure things work the way they should.

e6187af7aac6e526cda468f0de6dea6a7c391e80

In the future, we can set this as default to on for exporting the final depth as just the IDs instead of full object information.

Right now, if depth is 1 then it only shows IDs. If depth is 2 then the second level relationships are showing full object information so the way it works is not consistent.

**Comment by sc0ttkclark** [comment]
The code to enable more consistent responses for relationship depth is as follows:

`add_filter( 'pods_api_export_pod_item_level_export_ids_at_final_depth', '__return_true' );`
