### ISSUE TITLE
Fix formatting issues for date/time fields

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6389]
### Description

Pre 2.8 we fixed format issues eventually by using the jQuery datepicker `altField` option. This worked flawlessly and fixed most issues with date fields using custom formats.

Now with 2.8 release, all such issues are happening again.
I think we should implement a similar functionality in the React component like we did with jQuery to again, fix all such issues.

Related:

- https://github.com/pods-framework/pods/issues/5038
- https://github.com/pods-framework/pods/issues/6213 (See discussion below)
- https://github.com/pods-framework/pods/pull/5451 (PR for jQuery)
- https://github.com/pods-framework/pods/issues/6440

### Version

2.8+

**Comment by HmCody** [comment]
Not sure if this issue has been reported, but when I type directly into an HTML date field rather than picking from the editor, the month works normally (typing 12 gives me 12), but when I type into the day portion, I can only enter single digit days. For instance, if I type 12, what shows up when I hit the 1 key is 01 and then when I hit the 2 key it changes to 02. 

As bugs go, not major, but it could certainly cause some unexpected results.

**Comment by sc0ttkclark** [comment]
Fixed via https://github.com/pods-framework/pods/pull/6860
