### ISSUE TITLE
WooCommerce Product Shortcode inside template 

### ISSUE THREAD

**Issue by CloundNine** [pods-framework/pods#6415]
### Description

WooCommerce Product Shortcode (as below) to display a single related product work fine.

`[if related_products]`
`[each related_products]`
`<div class="landing-products">[products columns="1" ids="{@ID}"]</div>`
`[/each]`
`[else]`

Using an "Each" statement (as below)  to generate list of related product ids outside the WooCommerce Shortcode works fine 

`[if related_products]`
`<div class="test-products">[each related_products]{@ID},[/each]</div>`
`[/if]`

WooCommerce Product Shortcode using the data generated by the above (as below)  works fine - even with the trailing comma. 

`[products columns="4" ids="9281,9275,300,9276,"]`

WooCommerce Product Shortcode wrapping only the generation of the IDs with an each displays all published and not hidden products - related and unrelated - followed by the following code **e0BJRH0s[/pod_sub_template]“]**

`[if related_products]`
`<div class="test-products">[products columns="4" ids="[each related_products]{@ID},[/each]"]</div>`
`[/if]`

### Version

2.8.8.1

### Testing Instructions

Page using single ID https://whisperingsong.ca/curric-2022/celtic-calendar-2/

Page using Each to retrieve multiple IDs https://whisperingsong.ca/curric-2022/list-products/

**Comment by sc0ttkclark** [comment]
This one is tricky, I would suggest not attempting to use a shortcode to build another shortcode because that is definitely an area we do not support right now and probably don't intend to support it.

You probably could support this with a custom shortcode that builds the information to send to the other shortcode callback function (don't call a shortcode within a shortcode there either).
