### ISSUE TITLE
Shortcodes are not transformed in the_excerpt

### ISSUE THREAD

**Issue by erixtekila** [pods-framework/pods#7160]
### Description

https://docs.pods.io/displaying-pods/pods-templates/using-shortcodes-in-pods-templates/#page-header-1347
In this documentation page, it is stated that shortcodes are automatically rendered in auto templates when using `the_content`  or ` the_exerpt` (note the small typo in the documentation site).

It's true for the former, but wrong from `the_excerpt` content.

### Version

2.9.1

### Testing Instructions

1. Create a pod
2. Associate an auto template for its plural display.
3. The filter `the_excerpt` is proposed
4. Create a small template with `[gallery ids="1,2,3"]`
5. The result is wordpress outputing the shortcode clientside, not its tranformed output.

### Possible Workaround

Use `<?php echo do_shortcode('[gallery ids="1,2,3"]'); ?>` instead, inside the template.

**Comment by JoryHogeveen** [comment]
Hi @erixtekila 

I will update the documentation since this is indeed incorrect.

`the_excerpt` indeed doesn't parse shortcodes by default. If you need this functionality then you'll need to add the hook in your theme or a plugin. See this page for more info as it's not Pods related: https://wordpress.stackexchange.com/questions/42743/the-excerpt-and-shortcodes

Thanks for reporting!

Cheers, Jory
