### ISSUE TITLE
Ability to set MySQL indexes for Table Based fields

### ISSUE THREAD

**Issue by unknownnf** [pods-framework/pods#729]

**Comment by mastef** [comment]
I would recommend this. It's a tiny improvement with a big effect.

Right now I checked the slow-query mysql logs for non-indexed requests ( `log_queries_not_using_indexes ` in my.cnf ) and found a bunch. E.g. when checking queries like `$queued_documents = pods( 'queued_document' )->find( null , -1, 'processing>0 and png_finished=0 and finished=0 and failed=0' );` they ended up in the slow query log.

After adding indexes :

```
ALTER TABLE `wp_pods_queued_document` ADD INDEX `finished` (`finished`);
ALTER TABLE `wp_pods_queued_document` ADD INDEX `failed` (`failed`);
ALTER TABLE `wp_pods_queued_document` ADD INDEX `png_finished` (`png_finished`);
ALTER TABLE `wp_pods_queued_document` ADD INDEX `processing` (`processing`);
```

It's all fine and dandy now. ( Yes, it could be even better with adding a 4 column index, but the performance improvement is the biggest when adding _any_ index )

Since we're keeping versioning through pods exclusively, it would be good to have a flag in table-based pods that a field should be indexed, and then pods taking care of it. Otherwise we'd have to add a 2nd versioning system just for pods mysql tables.

**Comment by mastef** [comment]
As to where to add that option in the UI, I'd suggest adding it to the "advanced tab" on fields of a "table" type pod : 

"[ ] Index field (?)"
"(?) In case you're using this field in where clauses, indexing it can improve performance in lookups once your pod exceeds a certain size ( > 1000 entries )"

**Comment by lougreenwood** [comment]
👍
