### ISSUE TITLE
Relate to multiple post types or taxonomies in a pick field

### ISSUE THREAD

**Issue by c0rnbread** [pods-framework/pods#821]
I have a pod called CTA (Call to action). I need pick field to reference a landing page for my CTA. I want a single-select pick field where a user can choose from Pages (Extended post type) or a Custom Post Type called "Fitness Classes"

So, here's how I'm doing it:

I created a field in the CTA pod called "Landing Page"

Field Type: Relationship

Related to: Pages

Selection Type: Single Select

Format: Drop Down

Where statement: post_type = 'fitnessclasses' || post_type = 'page'

So far so good, The CTA pod has a single select menu that lists all the Pages and Fitness Classes. 

Here's where the problem is: If I select one of the Fitness Classes and save the pod, the page reloads and the value of the drop-down becomes "-- Select One --." If I select a page instead, the value remains as the page I selected.

**Comment by dboune** [comment]
#1609 appears to be related to this issue.

I have a need for this as well, where it would be possible to select up to a specific number of items from PodA that has a taxonomy of 'slug', and PodB.

While editing a PodA post.
Related Items (Max: 5):
 - Item 1 From PodA (which has the correct taxonomy)
 - Item 2 From PodB
 - Item 3 From PodA (which has the correct taxonomy)
 - Item 4 From PodB
 - Item 5 From PodB

When displaying be able to: Order by date, or by whatever field is the "title", or whatever other compatible field. Then, possibly depending on the related items pod type because fields may not match exactly, display whatever fields are needed.

The workarounds to all this are all pretty ugly from a usability perspective.

Would love to have this!

**Comment by jimtrue** [comment]
I don't think this is structurally sound. You would use multiple selection fields. Relationships aren't to multiple things in the same relationship but to one 'set' of related items. Our new flexible Relationships makes this concept not necessary anymore, I believe. #3311
